### PR TITLE
Merge fp16 headers for CUDA 11.2+

### LINKED ISSUE #5992: Support CUDA enhanced compatibility for CUDA 11.2+
Suggestion
-----------
Merge all subfolders of `cupy/_core/include/cupy/_cuda/cuda-11.X/*` into one for `X>=2`:
- `cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.h`
- `cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.hpp`

Context
--------
With https://github.com/cupy/cupy/pull/5723 CuPy has made a big step toward utilizing the CUDA 11 ABI compatibility. Specifically, CUDA 11.2+ provides a mean for future compatibility (ex: build on CUDA 11.2 and run on CUDA 11.4). This is also adopted by conda-forge to reduce the number of packages we upload (see https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/172).

However, the RAPIDS team found that it's not yet the case for CuPy v9 and likely v10, because of this branching:
https://github.com/cupy/cupy/blob/10914984e6989046cb8c9447b7f475237a7acf41/cupy/_core/core.pyx#L2079-L2093
Every time a new CUDA 11.x release is out, without supplying the new header we'd see a compilation error
```
$ conda create -n cupy_dev -c conda-forge python=3.8 cupy cudatoolkit=11.5  # cupy compiled with CUDA 11.2
$ conda activate cupy_dev
$ python -c "import cupy; a = cupy.arange(10)"
Traceback (most recent call last):
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 653, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 133, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 145, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 64, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/_creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/_core/_kernel.pyx", line 1185, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 1212, in cupy._core._kernel.ufunc._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 952, in cupy._core._kernel._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 62, in cupy._core._kernel._get_simple_elementwise_kernel
  File "cupy/_core/core.pyx", line 2042, in cupy._core.core.compile_with_cache
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 460, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 538, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 298, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 282, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 670, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/_core/include/cupy/carray.cuh(39): catastrophic error: cannot open source file "cuda_fp16.h"

1 catastrophic error detected in the compilation of "/tmp/tmpfrwmo62y/c13138d88f8c4f3dcd51b1a401808430_2.cubin.cu".
Compilation terminated.
```

cc: @jakirkham @pentschev

### PR DESCRIPTION
**Pull request by leofang**
Close #5992. Alternative option of #5991.

@kmaehashi I took your commits from #5991 so that this PR is ready for tests 🙂

### CODE REVIEW

**Comment by leofang** [comment]
This PR should run fine on CUDA 11.2+. Let's give it a shot.

Jenkins, test this please

**Comment by leofang** [comment]
Commit 43b6d2a passed all tests (except for flake8, which was fixed in the next commit). I think for CUDA <=11.4 this does not break anything; CUDA 11.5 can be tested on the new CI (cc: @kmaehashi).

**Comment by kmaehashi** [comment]
pfnCI, test this please.

Test for CUDA 11.5 triggered at: https://ci.preferred.jp/cupy.linux.cuda115/83432/

**Review by kmaehashi — DISMISSED** [review]

**Comment by leofang** [comment]
> Test for CUDA 11.5 triggered at: https://ci.preferred.jp/cupy.linux.cuda115/83432/

hmmm... driver is too new/old?
```
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorSystemDriverMismatch: system has unsupported display driver / cuda driver combination
```

**Comment by kmaehashi** [comment]
Local dev host (with CTK 11.4 (`libcuda.so.470.57.02`)) can run the Dockerfile in this PR, but FlexCI host (no CTK, `cuda-drivers=470.42.01-1`) fails `cudaErrorSystemDriverMismatch: system has unsupported display driver / cuda driver combination`. I thought the driver requirement for CUDA 11.x is `>= 450.80.02*` according to the [compatibility docs](https://docs.nvidia.com/deploy/cuda-compatibility/#default-to-minor-version) but seems there are another restrictions?

**Comment by kmaehashi** [comment]
Kicked test with the latest driver: https://ci.preferred.jp/cupy.linux.cuda115/83513/

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
> Kicked test with the latest driver: https://ci.preferred.jp/cupy.linux.cuda115/83513/

CUDA 11.5 tests passed! 🎉

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
All tests are green, thanks @leofang!
I will take care of backport.

**Comment by leofang** [comment]
Thank you, @kmaehashi!
