### ISSUE TITLE
NVRTC_ERROR_COMPILATION incomplete type __nv_fp8_e8m0

### ISSUE THREAD

**Issue by casperdcl** [cupy/cupy#9962]
### Description

error source: https://github.com/AMYPAD/CuVec/actions/runs/26348578914/job/77562717063#step:5:401

```cpp
...
cupy/_core/include/cupy/_cccl/libcudacxx/cuda/std/__floating_point/storage.h(137): error: incomplete type "__nv_fp8_e8m0" is not allowed
...
```

### To Reproduce

was [working in `cupy==13.6`](https://github.com/AMYPAD/CuVec/actions/runs/25977936674/job/76361368328), but [fails in `cupy==14.1`](https://github.com/AMYPAD/CuVec/actions/runs/26348578914/job/77562717063)

tests source: [AMYPAD/CuVec:/tests/test_common.py:test_cuda_array_interface](https://github.com/AMYPAD/CuVec/blob/26848fc234e35bff9368cef95e5ac57bc245b616/tests/test_common.py#L127)

```py
# create array using external library
import cuvec as cu, numpy as np
v = cu.asarray(np.random.random(shape))
assert set(v.__cuda_array_interface__) == {'shape', 'typestr', 'data', 'version'}
# convert to cupy array
c = cupy.asarray(v)
assert (c == v).all() # pass with cupy<=13.6, fail with cupy>=14.1
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-5.15.0-144-generic-x86_64-with-glibc2.35
Python Version               : 3.13.13
CuPy Version                 : 14.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.4.6
SciPy Version                : None
Cython Build Version         : 3.2.4
Cython Runtime Version       : None
CUDA Root                    : /opt/runner/runner01/miniconda/envs/py3.13-CuVec-26470327921.858/targets/x86_64-linux
NVCC PATH                    : None
CUDA Build Version           : 12090
CUDA Driver Version          : 12090
CUDA Runtime Version         : 12090 (linked to CuPy) / 12090 (locally installed)
CUDA Runtime Path            : /opt/runner/runner01/miniconda/envs/py3.13-CuVec-26470327921.858/lib/python3.13/lib-dynload/../../libcudart.so.12 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 120902
cuBLAS Path                  : /opt/runner/runner01/miniconda/envs/py3.13-CuVec-26470327921.858/lib/python3.13/lib-dynload/../../libcublas.so.12
cuFFT Version                : 11401
cuFFT Path                   : /opt/runner/runner01/miniconda/envs/py3.13-CuVec-26470327921.858/lib/python3.13/lib-dynload/../../libcufft.so.11
cuRAND Version               : 10310
cuRAND Path                  : /opt/runner/runner01/miniconda/envs/py3.13-CuVec-26470327921.858/lib/python3.13/lib-dynload/../../libcurand.so.10
cuSOLVER Version             : (11, 7, 5)
cuSOLVER Path                : /opt/runner/runner01/miniconda/envs/py3.13-CuVec-26470327921.858/lib/python3.13/lib-dynload/../../libcusolver.so.11
cuSPARSE Version             : 12510
cuSPARSE Path                : /opt/runner/runner01/miniconda/envs/py3.13-CuVec-26470327921.858/lib/python3.13/lib-dynload/../../libcusparse.so.12
NVRTC Version                : (12, 9)
NVRTC Path                   : /opt/runner/runner01/miniconda/envs/py3.13-CuVec-26470327921.858/lib/python3.13/lib-dynload/../../libnvrtc.so.12
Thrust Version               : 200802
CUB Build Version            : 300102
Jitify Build Version         : <unknown>
NCCL Build Version           : None
NCCL Runtime Version         : None
NCCL Path                    : None
cuTENSOR Version             : None
cuTENSOR Path                : None
cuSPARSELt Build Version     : None
cuSPARSELt Path              : None
Device 0 Name                : Tesla V100-PCIE-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:00:08.0
```

**Comment by leofang** [comment]
Hi Casper, this might be a packaging issue that I overlooked on conda-forge. Could you check if installing `cuda-cudart-dev` would fix it?

**Comment by leofang** [comment]
xref: https://docs.cupy.dev/en/stable/install.html#cupy-always-raises-nvrtc-error-compilation-6

**Comment by casperdcl** [comment]
[`conda install cuda-cudart-dev cupy=14.1 python=3.13`](https://github.com/AMYPAD/CuVec/actions/runs/26455547645/job/77888350077?pr=53#step:3:26) and rerunning the test results in [this error](https://github.com/AMYPAD/CuVec/actions/runs/26455547645/job/77888350077?pr=53#step:5:218):


```py
cupy/_core/core.pyx:1496: in cupy._core.core._ndarray_base.__richcmp__
cupy/_core/core.pyx:1977: in cupy._core.core._ndarray_base.__array_ufunc__
cupy/_core/_kernel.pyx:1397: in cupy._core._kernel.ufunc.__call__
cupy/_core/_kernel.pyx:1426: in cupy._core._kernel.ufunc._get_ufunc_kernel
cupy/_core/_kernel.pyx:1098: in cupy._core._kernel._get_ufunc_kernel
cupy/_core/_kernel.pyx:124: in cupy._core._kernel._get_simple_elementwise_kernel
cupy/_core/_kernel.pyx:112: in cupy._core._kernel._get_simple_elementwise_kernel_from_code
cupy/_core/core.pyx:2590: in cupy._core.core.compile_with_cache
cupy/_core/core.pyx:2552: in cupy._core.core.assemble_cupy_compiler_options
E   RuntimeError: Failed to find CUDA headers. Please install CUDA toolkit headers (e.g., pip install cupy-cuda12x[ctk]) or specify CUDA_PATH environment variable.
```

**Comment by leofang** [comment]
I unfortunately cannot reproduce either error. I will need the full outputs from `conda list` and `conda info` to reason about the issue. 

Just FYI, I don't think CUDA 13 works with V100 anymore. But I would expect a different error at JIT time, something like
```
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)
```
xref: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#deprecated-architectures

**Comment by casperdcl** [comment]
Thanks for checking - I linked the failing CI job so that you can see all the other debug info. Copy-pasting here for convenience (it's definitely pulling cuda 12.9):

```
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-20_gnu 
  bzip2              conda-forge/linux-64::bzip2-1.0.8-hda65f42_9 
  ca-certificates    conda-forge/noarch::ca-certificates-2026.5.20-hbd8a1cb_0 
  cuda-cccl_linux-64 conda-forge/noarch::cuda-cccl_linux-64-12.9.27-ha770c72_0 
  cuda-cudart        conda-forge/linux-64::cuda-cudart-12.9.79-h5888daf_0 
  cuda-cudart-dev    conda-forge/linux-64::cuda-cudart-dev-12.9.79-h5888daf_0 
  cuda-cudart-dev_l~ conda-forge/noarch::cuda-cudart-dev_linux-64-12.9.79-h3f2d84a_0 
  cuda-cudart-static conda-forge/linux-64::cuda-cudart-static-12.9.79-h5888daf_0 
  cuda-cudart-stati~ conda-forge/noarch::cuda-cudart-static_linux-64-12.9.79-h3f2d84a_0 
  cuda-cudart_linux~ conda-forge/noarch::cuda-cudart_linux-64-12.9.79-h3f2d84a_0 
  cuda-nvrtc         conda-forge/linux-64::cuda-nvrtc-12.9.86-hecca717_1 
  cuda-pathfinder    conda-forge/noarch::cuda-pathfinder-1.5.4-pyhc364b38_0 
  cuda-version       conda-forge/noarch::cuda-version-12.9-h4f385c5_3 
  cupy               conda-forge/linux-64::cupy-14.1.0-py313h7fc6698_0 
  cupy-core          conda-forge/linux-64::cupy-core-14.1.0-py313h28b6081_0 
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.45.1-default_hbd61a6d_102 
  libblas            conda-forge/linux-64::libblas-3.11.0-7_h4a7cf45_openblas 
  libcblas           conda-forge/linux-64::libcblas-3.11.0-7_h0358290_openblas 
  libcublas          conda-forge/linux-64::libcublas-12.9.2.10-h676940d_0 
  libcufft           conda-forge/linux-64::libcufft-11.4.1.4-hecca717_1 
  libcurand          conda-forge/linux-64::libcurand-10.3.10.19-h676940d_1 
  libcusolver        conda-forge/linux-64::libcusolver-11.7.5.82-h676940d_2 
  libcusparse        conda-forge/linux-64::libcusparse-12.5.10.65-hecca717_2 
  libexpat           conda-forge/linux-64::libexpat-2.8.1-hecca717_0 
  libffi             conda-forge/linux-64::libffi-3.5.2-h3435931_0 
  libgcc             conda-forge/linux-64::libgcc-15.2.0-he0feb66_19 
  libgfortran        conda-forge/linux-64::libgfortran-15.2.0-h69a702a_19 
  libgfortran5       conda-forge/linux-64::libgfortran5-15.2.0-h68bc16d_19 
  libgomp            conda-forge/linux-64::libgomp-15.2.0-he0feb66_19 
  liblapack          conda-forge/linux-64::liblapack-3.11.0-7_h47877c9_openblas 
  liblzma            conda-forge/linux-64::liblzma-5.8.3-hb03c661_0 
  libmpdec           conda-forge/linux-64::libmpdec-4.0.0-hb03c661_1 
  libnvjitlink       conda-forge/linux-64::libnvjitlink-12.9.86-hecca717_2 
  libopenblas        conda-forge/linux-64::libopenblas-0.3.33-pthreads_h94d23a6_0 
  libsqlite          conda-forge/linux-64::libsqlite-3.53.1-h0c1763c_0 
  libstdcxx          conda-forge/linux-64::libstdcxx-15.2.0-h934c35e_19 
  libuuid            conda-forge/linux-64::libuuid-2.42.1-h5347b49_0 
  libzlib            conda-forge/linux-64::libzlib-1.3.2-h25fd6f3_2 
  ncurses            conda-forge/linux-64::ncurses-6.6-hdb14827_0 
  numpy              conda-forge/linux-64::numpy-2.4.6-py313hf6604e3_0 
  openssl            conda-forge/linux-64::openssl-3.6.2-h35e630c_0 
  pip                conda-forge/noarch::pip-26.1.1-pyh145f28c_0 
  python             conda-forge/linux-64::python-3.13.13-h6add32d_100_cp313 
  python_abi         conda-forge/noarch::python_abi-3.13-8_cp313 
  readline           conda-forge/linux-64::readline-8.3-h853b02a_0 
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h366c992_103 
  tzdata             conda-forge/noarch::tzdata-2025c-hc9c84f9_1 
  zstd               conda-forge/linux-64::zstd-1.5.7-hb78ec9c_6 
```

Feel free to transfer this issue to https://github.com/conda-forge/cupy-feedstock if you think appropriate and/or open testing PRs similar to https://github.com/AMYPAD/CuVec/pull/53.

Briefly looking at the feedstock; is a build string prefix missing? Presumably installation could be something like `conda install cupy=*=cu12*`? right now maybe all the cuda version builds are being clobbered into the same build string?

**Comment by leofang** [comment]
Your [first env](https://github.com/cupy/cupy/issues/9962#issue-4516780192) has NVRTC and cuBLAS from CUDA 13. Only your [second env](https://github.com/cupy/cupy/issues/9962#issuecomment-4545391248) has CUDA 12. Also [your local runner has CUDA 12.4](https://github.com/AMYPAD/CuVec/actions/runs/26455547645/job/77888350077?pr=53#step:4:72). I would consider this test env corrupted.

**Comment by casperdcl** [comment]
Did a lot more debugging.

`/usr/local/cuda*` (regardless of version 12.4, 12.9, 13, etc) should be ignored by `conda-forge::cupy`

Interestingly I found this fix:

```diff
 conda create -n test cuda-cudart-dev cupy=14.1 python=3.13
-export PATH="miniconda/envs/test/bin:$PATH"
+conda activate test
```

which results in:

```diff
 import cupy; cupy.show_config(_full=True)
 OS                           : Linux-5.15.0-144-generic-x86_64-with-glibc2.35
 Python Version               : 3.13.13
 CuPy Version                 : 14.1.0
 CuPy Platform                : NVIDIA CUDA
 NumPy Version                : 2.4.6
 SciPy Version                : None
 Cython Build Version         : 3.2.4
 Cython Runtime Version       : None
 CUDA Root                    : miniconda/envs/test/targets/x86_64-linux
 NVCC PATH                    : None
 CUDA Build Version           : 12090
 CUDA Driver Version          : 12090
 CUDA Runtime Version         : 12090 (linked to CuPy) / 12090 (locally installed)
-CUDA Runtime Path            : miniconda/envs/test/lib/python3.13/lib-dynload/../../libcudart.so.12 (locally installed)
-CUDA Extra Include Dirs      : []
+CUDA Runtime Path            : miniconda/envs/test/lib/libcudart.so (locally installed)
+CUDA Extra Include Dirs      : ['miniconda/envs/test/targets/x86_64-linux/include']
 cuBLAS Version               : 120902
-cuBLAS Path                  : miniconda/envs/test/lib/python3.13/lib-dynload/../../libcublas.so.12
+cuBLAS Path                  : miniconda/envs/test/lib/libcublas.so.12.9.2.10
 cuFFT Version                : 11401
-cuFFT Path                   : miniconda/envs/test/lib/python3.13/lib-dynload/../../libcufft.so.11
+cuFFT Path                   : miniconda/envs/test/lib/libcufft.so.11.4.1.4
 cuRAND Version               : 10310
-cuRAND Path                  : miniconda/envs/test/lib/python3.13/lib-dynload/../../libcurand.so.10
+cuRAND Path                  : miniconda/envs/test/lib/libcurand.so.10.3.10.19
 cuSOLVER Version             : (11, 7, 5)
-cuSOLVER Path                : miniconda/envs/test/lib/python3.13/lib-dynload/../../libcusolver.so.11
+cuSOLVER Path                : miniconda/envs/test/lib/libcusolver.so.11.7.5.82
 cuSPARSE Version             : 12510
-cuSPARSE Path                : miniconda/envs/test/lib/python3.13/lib-dynload/../../libcusparse.so.12
+cuSPARSE Path                : miniconda/envs/test/lib/libcusparse.so.12.5.10.65
 NVRTC Version                : (12, 9)
-NVRTC Path                   : miniconda/envs/test/lib/python3.13/lib-dynload/../../libnvrtc.so.12
+NVRTC Path                   : miniconda/envs/test/lib/libnvrtc.so.12.9.86
 Thrust Version               : 200802
 CUB Build Version            : 300102
 Jitify Build Version         : <unknown>
 NCCL Build Version           : None
 NCCL Runtime Version         : None
 NCCL Path                    : None
 cuTENSOR Version             : None
 cuTENSOR Path                : None
 cuSPARSELt Build Version     : None
 cuSPARSELt Path              : None
 Device 0 Name                : Tesla V100-PCIE-32GB
 Device 0 Compute Capability  : 70
 Device 0 PCI Bus ID          : 0000:00:08.0
```

Yes, `conda activate` is more "correct" than manually adding to `PATH`, but it would be nice if `cupy`'s search logic could handle both.

**Comment by casperdcl** [comment]
Based on [`cuda.pathfinder.find_nvidia_headers.find_in_conda`](https://github.com/NVIDIA/cuda-python/blob/6959cb99fb239321eba2eba22e573b35a23d0a56/cuda_pathfinder/cuda/pathfinder/_headers/find_nvidia_headers.py#L89) I found I needed to `export CONDA_PREFIX`
