### PR TITLE
Fix C++ compilation error

### LINKED ISSUE #4875: [BUG] NVRTC does not support <type_traits> out of box
On the current master, this snippet
```python
import cupy as cp

code = r'''
#include <cupy/carray.cuh>

extern "C" __global__ void fff(float* a) {

   int tid = threadIdx.x;
   a[tid] += 1;
}
'''

mod = cp.RawModule(code=code, options=('-std=c++11',))
ker = mod.get_function("fff")
```
raises an exception:
```
cupy.cuda.compiler.CompileException: /home/leofang/dev/cupy_cuda112/cupy/core/include/cupy/carray.cuh(4): catastrophic error: cannot open source file "type_traits"
```
This is a regression due to #3683 adding this line:
https://github.com/cupy/cupy/blob/fa21dd5d43ea93a48ccfa3bd796da101cf4c1c7c/cupy/core/include/cupy/carray.cuh#L4
NVRTC does not support most of the C++ std headers, which is why we need Jitify. I don't know how come all tests managed to pass so far...🤔

### PR DESCRIPTION
**Pull request by leofang**
Close #4875.

As mentioned in the linked issue, NVRTC by default does not support many C++ features, including the offending `type_traits` header. Since it is best to not revert a feature we already supported (#3683), I choose to add a workaround patch, which in this case is still manageable though unfortunately against my earlier intention to avoid custom C++ `std` stubs (ex: #4264).

The added test ensures an error like the one reported in #4875 can be detected by the CI and prevents a regression from happening again.

cc: @takagi @coderforlife @grlee77

### CODE REVIEW

**Comment by coderforlife** [comment]
This is a much better approach to this. That std::enable_if is also used at https://github.com/cupy/cupy/blob/a0aa435b9459c2d5b9a1266edc6f670a1c903e34/cupyx/scipy/ndimage/_filters_core.py#L164-L170.

**Comment by leofang** [comment]
@coderforlife Do you think I should also substitute `std::enable_if` in `cupy/cupyx/scipy/ndimage/_filters_core.py`?

**Comment by leofang** [comment]
Jenkins, test this please

File: cupy/core/core.pyx [hunk 1]
```diff
@@ -1858,16 +1858,19 @@ cdef bint _is_hip = runtime._is_hip_environment
 cdef int _cuda_runtime_version = -1
 cdef str _cuda_path = ''  # '' for uninitialized, None for non-existing
 
-cdef list _cupy_header_list = [
+cdef list cupy_header_list = [
```
Comment (leofang) [inline cupy/core/core.pyx:1861]: This is a `cdef` variable defined in `.pyx`. I don't think we need to mark it private (by prepending an underscore), as it already is. No functions (either in Cython or Python) outside this module can access it.

File: tests/cupy_tests/core_tests/test_core.py [hunk 2]
```diff
@@ -1,11 +1,13 @@
 import unittest
+import sys
 
 import numpy
 import pytest
 
 import cupy
 from cupy.core import core
 from cupy import testing
+from .test_raw import use_temporary_cache_dir
```
Comment (takagi) [inline tests/cupy_tests/core_tests/test_core.py:10]: Would you use an absolute module path?

**Review by takagi — CHANGES_REQUESTED** [review]
LGTM except for one guideline issue!

File: tests/cupy_tests/core_tests/test_core.py (hunk 2 above)
Comment (leofang) [reply tests/cupy_tests/core_tests/test_core.py]: Done in 00d3594.

**Comment by leofang** [comment]
Jenkins, test this please

File: tests/cupy_tests/core_tests/test_core.py [hunk 3]
```diff
@@ -1,11 +1,13 @@
 import unittest
+import sys
 
 import numpy
 import pytest
 
 import cupy
 from cupy.core import core
 from cupy import testing
+from tests.cupy_tests.core_tests import test_raw
```
Comment (kmaehashi) [inline tests/cupy_tests/core_tests/test_core.py:10]:
```suggestion
from cupy_tests.core_tests import test_raw
```

Comment (leofang) [reply tests/cupy_tests/core_tests/test_core.py:10]: Thanks, @kmaehashi. I feel absolute importing from other test modules is shaky...

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by takagi** [comment]
Jenkins, test this please

**Review by takagi — APPROVED** [review]

**Comment by leofang** [comment]
@takagi NVRTC in CUDA < 11.1 does not support `--std=c++03`, so I took it away. On CUDA 11.2, I tested that it works.

**Comment by leofang** [comment]
Jenkins, test this please

**Review by takagi — APPROVED** [review]

**Comment by takagi** [comment]
Thanks! Will be merged soon once it passes.
