### ISSUE TITLE
About cupy build error in HIP (AMD ROCm) environment

### ISSUE THREAD

**Issue by KeigoTakamura** [cupy/cupy#2681]
Hello,I tried to build an environment based on ROCm for Cupy but failed
 I tried HIP build on "cupy v7.0.0 rc1" but it failed in some environments.
I have built and tried multiple environments and reproduced a similar error.

Env1 
OS Ubuntu 18.04.3
Xeon  E5-2603 v4
gcc 7.4.0
GPU RadeonⅦ
ROCm version 2.9.6
MiOpen Version: 2.1.0.7487-rocm-rel-2.9-6-a5a4129

Env2
Run on Env1
ROCm Docker based env
The same build error was reproduced in the following Dockerfile
https://gist.github.com/KeigoTakamura/188295b7a5a07215d90348c769af3dbc

Env3

OS ubuntu 18.04.3
eGPU Base  Dynabook U63 
CPU Corei5 7300U 
GPU Vega56
ROCm version 2.9.6

The following build errors were confirmed in the above environment

```
cupy/cuda/runtime.cpp: In function 'int __pyx_f_4cupy_4cuda_7runtime_deviceGetByPCIBusId(PyObject*, int)':
cupy/cuda/runtime.cpp:3966:83: error: 'cudaDeviceGetByPCIBusId' was not declared in this scope
   __pyx_v_status = cudaDeviceGetByPCIBusId((&__pyx_v_device), __pyx_v_c_pci_bus_id);
                                                                                   ^
cupy/cuda/runtime.cpp: In function 'PyObject* __pyx_f_4cupy_4cuda_7runtime_deviceGetPCIBusId(int, int)':
cupy/cuda/runtime.cpp:4076:80: error: 'cudaDeviceGetPCIBusId' was not declared in this scope
   __pyx_v_status = cudaDeviceGetPCIBusId(__pyx_v_pci_bus_id, 13, __pyx_v_device);
                                                                                ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
This error could not be reproduced in some environments of ubuntu16.04 LST, but this error was confirmed in multiple environments and machines

**Comment by okuta** [comment]
Thank you for your report!
Current HIP support experimental feature only supports AMD environment.

Please use normal CuPy when you use Nvidia GPU and CUDA.

**Comment by okuta** [comment]
This error was solved by #2632 . 
Could you try CuPy master branch?

**Comment by KeigoTakamura** [comment]
Thank you for checking the issue
I checked the operation on the ENV1 machine, but an error occurred.

```python ./setup.py develop```

```
cupy/cuda/driver.cpp:3491:26: error: ‘cuLinkAddFile’ was not declared in this scope
         __pyx_v_status = cuLinkAddFile(((CUlinkState)__pyx_v_state), ((CUjitInputType)__pyx_v_input_type), __pyx_v_b_path_ptr, 0, ((CUjit_option *)0), ((void **)0));
                          ^~~~~~~~~~~~~
cupy/cuda/driver.cpp:3491:26: note: suggested alternative: ‘cuLinkAddData’
         __pyx_v_status = cuLinkAddFile(((CUlinkState)__pyx_v_state), ((CUjitInputType)__pyx_v_input_type), __pyx_v_b_path_ptr, 0, ((CUjit_option *)0), ((void **)0));
                          ^~~~~~~~~~~~~
                          cuLinkAddData
error: command 'gcc' failed with exit status 1
```
>error: ‘cuLinkAddFile’ was not declared in this scope

I tried the master branch but got another error.

**Comment by leofang** [comment]
@KeigoTakamura This looks like my oversight when working on #2426, although I am not sure why it's not caught by the CI. Could you try the patch in #2737 and see if it works? Thanks.

**Comment by KeigoTakamura** [comment]
Thank you for quick response.
I checked the operation with env1
```
git clone git@github.com:leofang/cupy.git -b fix_hip_build
 cd ./cupy
python ./setup.py develop
```
I got another error.

```
cupy/cuda/cusolver.cpp:2179:48: error: ‘libraryPropertyType_t’ was not declared in this scope
         __pyx_v_status = cusolverGetProperty(((libraryPropertyType_t)__pyx_v_type), (&__pyx_v_value));
                                                ^~~~~~~~~~~~~~~~~~~~~
cupy/cuda/cusolver.cpp:2179:48: note: suggested alternative: ‘PyProperty_Type’
         __pyx_v_status = cusolverGetProperty(((libraryPropertyType_t)__pyx_v_type), (&__pyx_v_value));
                                                ^~~~~~~~~~~~~~~~~~~~~
                                                PyProperty_Type
cupy/cuda/cusolver.cpp:2179:70: error: expected ‘)’ before ‘__pyx_v_type’
         __pyx_v_status = cusolverGetProperty(((libraryPropertyType_t)__pyx_v_type), (&__pyx_v_value));
                                                                      ^~~~~~~~~~~~
cupy/cuda/cusolver.cpp: In function ‘PyObject* __pyx_f_4cupy_4cuda_8cusolver__getVersion(int)’:
cupy/cuda/cusolver.cpp:2313:78: error: ‘MAJOR_VERSION’ was not declared in this scope
   __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_f_4cupy_4cuda_8cusolver_getProperty(MAJOR_VERSION, 0)); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 456, __pyx_L1_error)
                                                                              ^~~~~~~~~~~~~
cupy/cuda/cusolver.cpp:2313:78: note: suggested alternative: ‘PY_MAJOR_VERSION’
   __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_f_4cupy_4cuda_8cusolver_getProperty(MAJOR_VERSION, 0)); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 456, __pyx_L1_error)
                                                                              ^~~~~~~~~~~~~
                                                                              PY_MAJOR_VERSION
cupy/cuda/cusolver.cpp:2323:78: error: ‘MINOR_VERSION’ was not declared in this scope
   __pyx_t_2 = __Pyx_PyInt_From_int(__pyx_f_4cupy_4cuda_8cusolver_getProperty(MINOR_VERSION, 0)); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 457, __pyx_L1_error)
                                                                              ^~~~~~~~~~~~~
cupy/cuda/cusolver.cpp:2323:78: note: suggested alternative: ‘PY_MINOR_VERSION’
   __pyx_t_2 = __Pyx_PyInt_From_int(__pyx_f_4cupy_4cuda_8cusolver_getProperty(MINOR_VERSION, 0)); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 457, __pyx_L1_error)
                                                                              ^~~~~~~~~~~~~
                                                                              PY_MINOR_VERSION
cupy/cuda/cusolver.cpp:2333:78: error: ‘PATCH_LEVEL’ was not declared in this scope
   __pyx_t_3 = __Pyx_PyInt_From_int(__pyx_f_4cupy_4cuda_8cusolver_getProperty(PATCH_LEVEL, 0)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 458, __pyx_L1_error)
                                                                              ^~~~~~~~~~~
error: command 'gcc' failed with exit status 1
```
>‘libraryPropertyType_t’ was not declared in this scope

Is there a problem with my environment?

**Comment by leofang** [comment]
No, your environment is fine. It's just that the HIP support is rather new, so when we make changes to the cuda codebase, we often forget to (or don't know we should) add necessary stubs for HIP. In this case, I think `libraryPropertyType_t` was added in #2578.

**Comment by leofang** [comment]
@KeigoTakamura Could you try again the patch from the same PR? I added a stub for `libraryPropertyType_t`. (Sorry I don't have an AMD card to test it myself...)

**Comment by KeigoTakamura** [comment]
>>Finished processing dependencies for cupy==7.0.0rc1



Build succeeded
Thank you for a good job!!!!!
