### ISSUE TITLE
`pip install cupy` is not correcly installing cupyx

### ISSUE THREAD

**Issue by bsugerman** [cupy/cupy#2654]
I'm installing cupy on a windows 10 machine running 3.7.3 and cuda 9.0. I've installed cupy successfully using `pip install cupy-cuda90`, in that the installation ends without error and I can use basic cupy functions. But when I try to get into the scipy packages, I find that some of them aren't installing on my machine (ex: `scipy.ndimage.filters`) and none of the scipy modules can be loaded.

     >>> cp.cupyx.scipy.ndimage
      AttributeError: module 'cupyx.scipy' has no attribute 'ndimage'

I'm also getting this error:
```
     >>> import cupy.cupyx.scipy as s
     ModuleNotFoundError: No module named 'cupy.cupyx'

```
but this works:
```
      from cupy import cupyx
      from cupyx import scipy
```

**Comment by leofang** [comment]
There's nothing wrong with your `pip`. That's simply because `cupyx` is not placed in the `cupy` namespace. If you need `ndimage`, just do
```python
>>> from cupyx.scipy import ndimage
```
It is made so to follow `scipy`'s practice: 
```python
>>> import scipy
>>> scipy.ndimage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scipy' has no attribute 'ndimage'
>>> from scipy import ndimage  # this works 
>>> 
```

**Comment by bsugerman** [comment]
OK, that worked.  But... is there any reason why the following will not work?

```
import cupy
from cupy.cupyx import scipy
```
instead, I have to do this cascade:
```
import cupy
from cupy import cupyx
from cupyx import scipy
```

Seems like an odd setup in the __init.py__

**Comment by grlee77** [comment]
I don't think you have to do that cascade. Just

```from cupyx import scipy```

should work on its own.

**Comment by toslunar** [comment]
It is not intended but `cupy.cupyx` is there just because `cupy/__init__.py` has the line `import cupyx`, which is similar to `numpy.sys` is the built-in `sys` module.

**Comment by leofang** [comment]
That being said, I also found the `cupyx` import a bit un-intuitive. I actually had made a similar request back in https://github.com/cupy/cupy/pull/1746#issuecomment-447600777. Do we really want to stick to `scipy` on this matter?

**Comment by kmaehashi** [comment]
We discussed and it is better to avoid exposing `cupy.cupyx` as it is confusing. @toslunar will send a PR to fix this issue.
@toslunar Could you close this issue after sending PR?
