### ISSUE TITLE
Support CUDA enhanced compatibility for CUDA 11.2+

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5992]
Suggestion
-----------
Merge all subfolders of `cupy/_core/include/cupy/_cuda/cuda-11.X/*` into one for `X>=2`:
- `cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.h`
- `cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.hpp`

Context
--------
With https://github.com/cupy/cupy/pull/5723 CuPy has made a big step toward utilizing the CUDA 11 ABI compatibility. Specifically, CUDA 11.2+ provides a mean for future compatibility (ex: build on CUDA 11.2 and run on CUDA 11.4). This is also adopted by conda-forge to reduce the number of packages we upload (see https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/172).

However, the RAPIDS team found that it's not yet the case for CuPy v9 and likely v10, because of this branching:
https://github.com/cupy/cupy/blob/10914984e6989046cb8c9447b7f475237a7acf41/cupy/_core/core.pyx#L2079-L2093
Every time a new CUDA 11.x release is out, without supplying the new header we'd see a compilation error
```
$ conda create -n cupy_dev -c conda-forge python=3.8 cupy cudatoolkit=11.5  # cupy compiled with CUDA 11.2
$ conda activate cupy_dev
$ python -c "import cupy; a = cupy.arange(10)"
Traceback (most recent call last):
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 653, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 133, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 145, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 64, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/_creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/_core/_kernel.pyx", line 1185, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 1212, in cupy._core._kernel.ufunc._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 952, in cupy._core._kernel._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 62, in cupy._core._kernel._get_simple_elementwise_kernel
  File "cupy/_core/core.pyx", line 2042, in cupy._core.core.compile_with_cache
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 460, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 538, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 298, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 282, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 670, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /home/leof/miniforge3/envs/cupy_dev/lib/python3.8/site-packages/cupy/_core/include/cupy/carray.cuh(39): catastrophic error: cannot open source file "cuda_fp16.h"

1 catastrophic error detected in the compilation of "/tmp/tmpfrwmo62y/c13138d88f8c4f3dcd51b1a401808430_2.cubin.cu".
Compilation terminated.
```

cc: @jakirkham @pentschev

**Comment by kmaehashi** [comment]
+1. :+1:

When I decided to include fp16 headers in CuPy I wasn't confident whether these headers bundled with the latest CUDA can be built with earlier versions of CUDA. Now that is guaranteed there's no reason to have separate headers for each CUDA minor version.

**Comment by leofang** [comment]
> When I decided to include fp16 headers in CuPy I wasn't confident whether these headers bundled with the latest CUDA can be built with earlier versions of CUDA. Now that is guaranteed there's no reason to have separate headers for each CUDA minor version.

Yes, I confirmed internally that you can take e.g. the headers from CTK 11.2 and run on 11.5, and vice versa.
