### PR TITLE
replace `cupy.pad` with a heavily refactored version from NumPy 1.17

### LINKED ISSUE #2367: Implement 'circular' or 'wrap' mode for cupy.pad
I'm working on 2D convolution problem but need circular (wrap) padding. Would that be hard implement a wrap mode like numpy? 

https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html

### PR DESCRIPTION
**Pull request by grlee77**
Enhancements to `cupy.pad` as discussed in #2367.

The only mode from `numpy.pad` that is omitted here is `median` due to the absence of `cupy.median`.

Aside from supporting a wider range of boundary modes, performance for the existing modes is 2-3 times faster on my machine. This is due to the performance-related refactorings done for NumPy 1.17 in PRs like numpy/numpy#11358 and numpy/numpy#11954. 

So far all padding tests pass locally when I tried them with NumPy 1.17 / Python 3.7.

**TODO?**
-  [x] include ~proposed~ bug fix for integer overflow from numpy/numpy#14209 
- [x] may want to merge #2330 first as this can cause inconsistent behavior for modes `mean` and `linear_ramp.

closes #2367

### CODE REVIEW

File: cupy/padding/pad.py [hunk 1]
```diff
@@ -1,321 +1,788 @@
-import numpy
-import six
+from __future__ import division, absolute_import, print_function
```
Comment (asi1024) [inline cupy/padding/pad.py]: CuPy will drop support for Python2 from the next version, so we don't have to use it.

File: cupy/padding/pad.py [hunk 2]
```diff
@@ -1,321 +1,788 @@
...
-        Padded array of rank equal to ``array`` with shape increased according
-        to ``pad_width`` .
+      nested iterables, shape (`ndim`, 2): The broadcasted version of `x`.
+    """
+    if x is None:
+        # Pass through None as a special case, otherwise cupy.round(x) fails
+        # with an AttributeError
+        return ((None, None),) * ndim
+
+    x = numpy.array(x)
```
Comment (asi1024) [inline cupy/padding/pad.py]: Could you explain why is it need to convert to `numpy.ndarray`? Is it typo of `cupy.asarray(x)`?

File: cupy/padding/pad.py [hunk 3]
```diff
@@ -1,321 +1,788 @@
...
-    narray = cupy.array(array)
-    pad_width = _validate_lengths(narray, pad_width)
-    allowed_keywords = {
-        'constant': ['constant_values'],
-        'edge': [],
-        'reflect': ['reflect_type'],
+    array = cupy.asarray(array)
+    pad_width = numpy.asarray(pad_width)
+
+    if not pad_width.dtype.kind == "i":
```
Comment (asi1024) [inline cupy/padding/pad.py]: Could you use single quotes from the consistency?
```suggestion
    if not pad_width.dtype.kind == 'i':
```

File: cupy/padding/pad.py (hunk 2 above)
Comment (grlee77) [reply cupy/padding/pad.py]: It is not a typo.  This `_as_pairs` function is basically just a utility that expands a user specified `pad_width` like to `2`, to its full form with a pre/post pad value for each axis (e.g.  `[(2, 2), (2, 2)]` in 2D).  This function uses `np.broadcast_to` to do this, but the returned values are a standard python list.  Given that the numpy arrays are just internal to this utility there is no reason to incur the overhead of transfer to/from the GPU.

File: cupy/padding/pad.py (hunk 3 above)
Comment (grlee77) [reply cupy/padding/pad.py]: Okay. I have changed instances of `"` to `'` except for strings containing other `'` internally.

**Comment by jakirkham** [comment]
Would it be possible to get another review here? Seems like the previous concerns raised were addressed. 🙂

File: cupy/padding/pad.py [hunk 4]
```diff
@@ -1,321 +1,786 @@
...
-    -------
-    padarr : ndarray
-        Output array, extended by `pad_amt` edge values appended along `axis`.
+    # Make sure, that ramp is broadcastable
+    init_shape = (1,) * axis + (size,) + (1,) * (ndim - axis - 1)
+    ramp = ramp.reshape(init_shape)
 
+    if size != 0:
+        # And scale to given start and stop values
+        gain = (stop - start) / float(size)
```
[the remark this answers is not in the document]
Comment (grlee77) [reply cupy/padding/pad.py]: yeah, this was listed as a TODO for the first comment. I see that those PRs have been merged now, so I will make the corresponding changes here.

[the remark this answers is not in the document]
Comment (grlee77) [reply cupy/padding/pad.py]: I added the changes from numpy/numpy#14209, but had to fall back to numpy's linspace since the `axis` argument is not implemented in `cupy.linspace`. That can probably be done, but should be a separate PR.

File: cupy/padding/pad.py [hunk 5]
```diff
@@ -1,321 +1,738 @@
+import cupy
 import numpy
-import six
+from numpy.lib.index_tricks import ndindex
```
Comment (asi1024) [inline cupy/padding/pad.py]: In this project, importing non-module symbols is prohibited. Why not writing just as `numpy.ndindex` without importing `lib.index_tricks`?

File: cupy/padding/pad.py [hunk 6]
```diff
@@ -1,321 +1,738 @@
+import cupy
```
Comment (asi1024) [inline cupy/padding/pad.py]: Import statements must be organized into three parts: standard libraries, third-party libraries, and internal imports. [H306]
Could you move this line after numpy imports?

File: cupy/padding/pad.py [hunk 7]
```diff
@@ -1,321 +1,738 @@
...
 import numpy
-import six
+from numpy.lib.index_tricks import ndindex
 
-import cupy
 
+__all__ = ['pad']
```
Comment (asi1024) [inline cupy/padding/pad.py]: In this project, we don't hide unused functions conventionally.

File: tests/cupy_tests/padding_tests/test_pad.py [hunk 8]
```diff
@@ -21,6 +22,11 @@ class TestPadDefault(unittest.TestCase):
     def test_pad_default(self, xp, dtype):
         array = xp.array(self.array, dtype=dtype)
 
+        if (xp.dtype(dtype).kind in ['i', 'u'] and
+                self.mode in ['mean', 'linear_ramp']):
+            # TODO: can remove this skip once cupy/cupy/#2330 is merged
+            return array
```
Comment (asi1024) [inline tests/cupy_tests/padding_tests/test_pad.py]: How about calling `self.skipTest`?

File: tests/cupy_tests/padding_tests/test_pad.py [hunk 9]
```diff
@@ -10,7 +10,8 @@
     *testing.product({
         'array': [numpy.arange(6).reshape([2, 3])],
         'pad_width': [1, [1, 2], [[1, 2], [3, 4]]],
-        'mode': ['constant', 'edge', 'reflect'],
+        'mode': ['constant', 'edge', 'reflect', 'maximum', 'minimum', 'mean',
+                 'symmetric', 'wrap', 'linear_ramp'],
```
Comment (asi1024) [inline tests/cupy_tests/padding_tests/test_pad.py]: ~Can we add `median` too?~
Sorry, I noticed that it is not implemented yet.

Comment (asi1024) [reply tests/cupy_tests/padding_tests/test_pad.py]: Could you sort in lexicographic order for the readability?

File: tests/cupy_tests/padding_tests/test_pad.py (hunk 8 above)
Comment (asi1024) [reply tests/cupy_tests/padding_tests/test_pad.py]: Sorry, the function decorated with `@testing.numpy_cupy_array_equal` can't use self.skipTest`. 🙇

Comment (grlee77) [reply tests/cupy_tests/padding_tests/test_pad.py]: Hi @asi1024, I have reverted the skipTest change. Can you run the CI again? Thanks

**Comment by asi1024** [comment]
pfnCI, test this please.

File: cupy/padding/pad.py [hunk 10]
```diff
@@ -1,321 +1,735 @@
...
+      nested iterables, shape (`ndim`, 2): The broadcasted version of `x`.
+    """
+    if x is None:
+        # Pass through None as a special case, otherwise cupy.round(x) fails
+        # with an AttributeError
+        return ((None, None),) * ndim
+
+    x = numpy.array(x)
+    if as_index:
+        x = numpy.round(x).astype(numpy.intp, copy=False)
```
Comment (asi1024) [inline cupy/padding/pad.py]: This line does not work in NumPy 1.9 because it does not support `copy` keyword argument. It looks not performance-critical. How about writing `x = numpy.round(x).astype(numpy.intp)` simply?

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by grlee77** [comment]
I see there is now a failure in some versions for linear_ramp:
`linspace() got an unexpected keyword argument 'axis'`.

I think that `axis` kwarg is only present in NumPy 1.16+. We can either only test that case for NumPy 1.16+ or review/merge #2461

**Comment by grlee77** [comment]
There was also a failure for mode `mean` that seems to just be a precision issue. Not sure yet on the exact underlying cause:  https://jenkins.preferred.jp/job/chainer/job/cupy_pr/367/TEST=cupy-py2,label=mn1-p100/testReport/junit/tests.cupy_tests.padding_tests.test_pad/TestPad_param_12/test_pad/

**Comment by grlee77** [comment]
It also appears that `numpy.broadcast_to` was only added in NumPy 1.10. This is causing many other Chainer test failures.

**Comment by grlee77** [comment]
Okay, I ran the CuPy padding tests locally with NumPy 1.9 and everything passes now.

We can update/simplyify these workarounds if #2461 is merged and/or minimum supported NumPy gets bumped to 1.10.

File: cupy/padding/pad.py [hunk 11]
```diff
@@ -1,321 +1,744 @@
...
+      width_pair((int, int)): Pair of widths that mark the pad area on both
+          sides in the given dimension.
+      end_value_pair((scalar, scalar)): End values for the linear ramps which
+          form the edge of the fully padded array. These values are included in
+          the linear ramps.
+    """
+    edge_pair = _get_edges(padded, axis, width_pair)
+
+    # TODO: implement axis argument to cupy.linspace to avoid need for numpy
+    if numpy.lib.NumpyVersion(numpy.__version__) >= '1.16.0':
```
Comment (asi1024) [inline cupy/padding/pad.py]:
```suggestion
    if numpy.lib.NumpyVersion(numpy.__version__) < '1.16.0':
```

File: cupy/padding/pad.py [hunk 12]
```diff
@@ -1,321 +1,744 @@
...
+    if as_index and x.min() < 0:
+        raise ValueError("index can't contain negative values")
+
+    # Converting the array with `tolist` seems to improve performance
+    # when iterating and indexing the result (see usage in `pad`)
+    try:
+        return numpy.broadcast_to(x, (ndim, 2)).tolist()
+    except AttributeError:
+        # NumPy < 1.10 does not have broadcast_to
+        return cupy.broadcast_to(cupy.asarray(x), (ndim, 2)).tolist()
```
Comment (asi1024) [inline cupy/padding/pad.py]: We don't want it to fallback to cupy routines for the performance.
How about rewriting `x.shape` directly
```suggestion
        x.shape = (ndim, 2)
        return x
```
or using `numpy.repeat`?
```suggestion
        return numpy.repeat(x, ndim * 2 // x.size).reshape(ndim, 2)
```
I think the former one is more appropriate.

Comment (grlee77) [reply cupy/padding/pad.py]: Setting the shape attribute seems to work and is very fast. It takes only a few hundred nanoseconds vs. a few microseconds for `np.broadcast_to` on my system.

Comment (grlee77) [reply cupy/padding/pad.py]: I couldn't think of a case where broadcast_to should work when setting the shape shouldn't, so I will just use your suggestion all NumPy versions. thanks

File: cupy/padding/pad.py (hunk 11 above)
Comment (grlee77) [reply cupy/padding/pad.py]: whoops! have fixed this now

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by grlee77** [comment]
Looks like the only failures now are unrelated to this PR (some `TestCrossProduct` cases on Python 2)

**Comment by jakirkham** [comment]
@grlee77, maybe merging with `master` helps? Seems there are not failures there.

@asi1024, any other ideas on how we can get this PR to go green? Would be nice to get this one in 🙂

**Comment by grlee77** [comment]
@jakirkham, I just rebased on current master so I could also squash several of the small code style commits. Hopefully it will pass all CI cases now.

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by grlee77** [comment]
Okay, there is one failure related to precision with pad mode `mean`. I was not able to reproduce locally when I last worked on this, but perhaps we should add a lower tolerance for the comparison in that case?

I think NumPy uses Pairwise Summation in sum() and mean() to improve accuracy, but don't know if CuPy also does this?

**Comment by grlee77** [comment]
splitting out the case for mode='mean' to use `numpy_cupy_array_almost_equal(decimal=5)` instead of `numpy_cupy_array_equal` will hopefully fix this last case

**Comment by asi1024** [comment]
pfnCI, test this please.

File: cupy/padding/pad.py [hunk 13]
```diff
@@ -1,321 +1,742 @@
...
+      axis(int): Dimension in which the ramps are constructed.
+      width_pair((int, int)): Pair of widths that mark the pad area on both
+          sides in the given dimension.
+      end_value_pair((scalar, scalar)): End values for the linear ramps which
+          form the edge of the fully padded array. These values are included in
+          the linear ramps.
+    """
+    edge_pair = _get_edges(padded, axis, width_pair)
+
+    # TODO: implement axis argument to cupy.linspace to avoid need for numpy
```
Comment (niboshi) [inline cupy/padding/pad.py]: Please add your name after `TODO`s. (`TODO(name): blah`)

File: cupy/padding/pad.py [hunk 14]
```diff
@@ -1,321 +1,742 @@
...
-                            axis=axis)
+def _round_if_needed(arr, dtype):
+    """Rounds arr inplace if destination dtype is integer.
+    """
+    if cupy.issubdtype(dtype, cupy.integer):
+        arr.round(out=arr)  # bug in round so use rint (cupy/cupy#2330)
+
+
+def _slice_at_axis(sl, axis):
+    """Construct tuple of slices to slice an array in the given dimension.
```
Comment (niboshi) [inline cupy/padding/pad.py]: Please use third-party singular present form for function docstrings.
(ditto for all other functions)

File: cupy/padding/pad.py [hunk 15]
```diff
@@ -1,321 +1,742 @@
...
+    Args:
+      array(array_like of rank N): The array to pad.
+      pad_width({sequence, array_like, int}): Number of values padded to the
+          edges of each axis. ((before_1, after_1), ... (before_N, after_N))
+          unique pad widths for each axis. ((before, after),) yields same
+          before and after pad for each axis. (pad,) or int is a shortcut for
+          before = after = pad width for all axes.
+      mode(str or function, optional): One of the following string
+          values or a user supplied function.
+          'constant' (default)
```
Comment (niboshi) [inline cupy/padding/pad.py]: This definition list does not seem rendered properly. Please fix it.

File: cupy/padding/pad.py [hunk 16]
```diff
@@ -1,321 +1,742 @@
...
+          'symmetric'.  The 'even' style is the default with an unaltered
+          reflection around the edge value.  For the 'odd' style, the extended
+          part of the array is created by subtracting the reflected values from
+          two times the edge value.
 
+    Returns:
+      ndarray: Padded array of rank equal to `array` with shape increased
+      according to `pad_width`.
+
+    Notes
```
Comment (niboshi) [inline cupy/padding/pad.py]: Please use `.. note::`

**Comment by pentschev** [comment]
On the PFN-NVIDIA meeting today this PR was briefly discussed and it won't land on CuPy 6.x as this is a new feature, and those don't get backported. However, a merge will be attempted before the release on Thursday.

cc @jakirkham

File: cupy/padding/pad.py (hunk 15 above)
Comment (grlee77) [reply cupy/padding/pad.py]: it should be fixed now. please take a look

File: cupy/padding/pad.py (hunk 14 above)
Comment (grlee77) [reply cupy/padding/pad.py]: I tried to update these, but not sure if I always did it exactly how you wanted. Feel free to make additional edits by pushing to my branch if that is easier than commenting individually.

I guess `pad` itself is the only function in the module that shows up in the user documentation, so we should pay closest attention to that one. The rendering of that looks much better after the latest commit.

**Comment by jakirkham** [comment]
Anything else needed here?

File: cupy/padding/pad.py [hunk 17]
```diff
@@ -1,321 +1,744 @@
...
+# Public functions
+
+
+# @array_function_dispatch(_pad_dispatcher, module='numpy')
+def pad(array, pad_width, mode='constant', **kwargs):
+    """Pads an array with specified widths and values.
 
-    .. seealso:: :func:`numpy.pad`
+    Args:
+      array(array_like of rank N): The array to pad.
```
Comment (asi1024) [inline cupy/padding/pad.py]: cupy functions won't accept numpy arrays because it could lead to hidden device synchronization.
```suggestion
      array(cupy.ndarray): The array of rank N to pad.
```

File: cupy/padding/pad.py [hunk 18]
```diff
@@ -1,321 +1,744 @@
...
+      pad_width({sequence, array_like, int}): Number of values padded to the
```
Comment (asi1024) [inline cupy/padding/pad.py]:
```suggestion
      pad_width(sequence, array_like or int): Number of values padded to the
```

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins failure seems unrelated to this PR. LGTM.
Thank you for the PR!

**Comment by jakirkham** [comment]
Thanks @grlee77! Also thanks for the reviews @asi1024! 😄
