### ISSUE TITLE
Build with AMD ROCm3.5.0 failed

### ISSUE THREAD

**Issue by alphaRGB** [cupy/cupy#3783]
Thank you for using and contributing to CuPy!

## Env
  - CuPy version: None
  - OS/Platform: Ubuntu 18.04 LTS
  - ROCm version: 3.5.0
  - cuDNN/NCCL version (if applicable)
  - Python: 3.7.4

I have install ROCm properly, I have compiled and run tensorflow-rocm successfully. But when I compile `cupy`  form source of this repo, I met there errors, Is cupy don't support ROCm3.5.0 ?

## Error messages, stack traces, or logs

```
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcCloseMemHandle(intptr_t, int)’:
cupy_backends/cuda/api/runtime.cpp:5531:20: error: ‘cudaIpcCloseMemHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcCloseMemHandle(((void *)__pyx_v_devPtr));
                    ^~~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5531:20: note: suggested alternative: ‘hipIpcCloseMemHandle’
   __pyx_v_status = cudaIpcCloseMemHandle(((void *)__pyx_v_devPtr));
                    ^~~~~~~~~~~~~~~~~~~~~
                    hipIpcCloseMemHandle
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcGetEventHandle(intptr_t, int)’:
cupy_backends/cuda/api/runtime.cpp:5622:3: error: ‘cudaIpcEventHandle_t’ was not declared in this scope
   cudaIpcEventHandle_t __pyx_v_handle;
   ^~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5622:3: note: suggested alternative: ‘hipIpcEventHandle_t’
   cudaIpcEventHandle_t __pyx_v_handle;
   ^~~~~~~~~~~~~~~~~~~~
   hipIpcEventHandle_t
cupy_backends/cuda/api/runtime.cpp:5640:44: error: ‘__pyx_v_handle’ was not declared in this scope
   __pyx_v_status = cudaIpcGetEventHandle((&__pyx_v_handle), ((cudaEvent_t)__pyx_v_event));
                                            ^~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5640:44: note: suggested alternative: ‘__pyx_k_handle’
   __pyx_v_status = cudaIpcGetEventHandle((&__pyx_v_handle), ((cudaEvent_t)__pyx_v_event));
                                            ^~~~~~~~~~~~~~
                                            __pyx_k_handle
cupy_backends/cuda/api/runtime.cpp:5640:20: error: ‘cudaIpcGetEventHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcGetEventHandle((&__pyx_v_handle), ((cudaEvent_t)__pyx_v_event));
                    ^~~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5640:20: note: suggested alternative: ‘hipIpcGetEventHandle’
   __pyx_v_status = cudaIpcGetEventHandle((&__pyx_v_handle), ((cudaEvent_t)__pyx_v_event));
                    ^~~~~~~~~~~~~~~~~~~~~
                    hipIpcGetEventHandle
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcGetMemHandle(intptr_t, int)’:
cupy_backends/cuda/api/runtime.cpp:5766:3: error: ‘cudaIpcMemHandle_t’ was not declared in this scope
   cudaIpcMemHandle_t __pyx_v_handle;
   ^~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5766:3: note: suggested alternative: ‘hipIpcMemHandle_t’
   cudaIpcMemHandle_t __pyx_v_handle;
   ^~~~~~~~~~~~~~~~~~
   hipIpcMemHandle_t
cupy_backends/cuda/api/runtime.cpp:5784:42: error: ‘__pyx_v_handle’ was not declared in this scope
   __pyx_v_status = cudaIpcGetMemHandle((&__pyx_v_handle), ((void *)__pyx_v_devPtr));
                                          ^~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5784:42: note: suggested alternative: ‘__pyx_k_handle’
   __pyx_v_status = cudaIpcGetMemHandle((&__pyx_v_handle), ((void *)__pyx_v_devPtr));
                                          ^~~~~~~~~~~~~~
                                          __pyx_k_handle
cupy_backends/cuda/api/runtime.cpp:5784:20: error: ‘cudaIpcGetMemHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcGetMemHandle((&__pyx_v_handle), ((void *)__pyx_v_devPtr));
                    ^~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5784:20: note: suggested alternative: ‘hipIpcGetMemHandle’
   __pyx_v_status = cudaIpcGetMemHandle((&__pyx_v_handle), ((void *)__pyx_v_devPtr));
                    ^~~~~~~~~~~~~~~~~~~
                    hipIpcGetMemHandle
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcOpenEventHandle(PyObject*, int)’:
cupy_backends/cuda/api/runtime.cpp:5911:3: error: ‘cudaIpcEventHandle_t’ was not declared in this scope
   cudaIpcEventHandle_t __pyx_v_handle_;
   ^~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5911:3: note: suggested alternative: ‘hipIpcEventHandle_t’
   cudaIpcEventHandle_t __pyx_v_handle_;
   ^~~~~~~~~~~~~~~~~~~~
   hipIpcEventHandle_t
cupy_backends/cuda/api/runtime.cpp:5927:12: error: ‘__pyx_v_handle_’ was not declared in this scope
   memcpy(&(__pyx_v_handle_.reserved[0]), __pyx_t_1, sizeof(__pyx_v_handle_.reserved[0]) * (64));
            ^~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5927:12: note: suggested alternative: ‘__pyx_v_handle’
   memcpy(&(__pyx_v_handle_.reserved[0]), __pyx_t_1, sizeof(__pyx_v_handle_.reserved[0]) * (64));
            ^~~~~~~~~~~~~~~
            __pyx_v_handle
cupy_backends/cuda/api/runtime.cpp:5936:20: error: ‘cudaIpcOpenEventHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcOpenEventHandle((&__pyx_v_event), __pyx_v_handle_);
                    ^~~~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5936:20: note: suggested alternative: ‘hipIpcOpenEventHandle’
   __pyx_v_status = cudaIpcOpenEventHandle((&__pyx_v_event), __pyx_v_handle_);
                    ^~~~~~~~~~~~~~~~~~~~~~
                    hipIpcOpenEventHandle
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcOpenMemHandle(PyObject*, int, __pyx_opt_args_13cupy_backends_4cuda_3api_7runtime_ipcOpenMemHandle*)’:
cupy_backends/cuda/api/runtime.cpp:6036:3: error: ‘cudaIpcMemHandle_t’ was not declared in this scope
   cudaIpcMemHandle_t __pyx_v_handle_;
   ^~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:6036:3: note: suggested alternative: ‘hipIpcMemHandle_t’
   cudaIpcMemHandle_t __pyx_v_handle_;
   ^~~~~~~~~~~~~~~~~~
   hipIpcMemHandle_t
cupy_backends/cuda/api/runtime.cpp:6057:12: error: ‘__pyx_v_handle_’ was not declared in this scope
   memcpy(&(__pyx_v_handle_.reserved[0]), __pyx_t_1, sizeof(__pyx_v_handle_.reserved[0]) * (64));
            ^~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:6057:12: note: suggested alternative: ‘__pyx_v_handle’
   memcpy(&(__pyx_v_handle_.reserved[0]), __pyx_t_1, sizeof(__pyx_v_handle_.reserved[0]) * (64));
            ^~~~~~~~~~~~~~~
            __pyx_v_handle
cupy_backends/cuda/api/runtime.cpp:6066:20: error: ‘cudaIpcOpenMemHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcOpenMemHandle((&__pyx_v_devPtr), __pyx_v_handle_, __pyx_v_flags);
                    ^~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:6066:20: note: suggested alternative: ‘hipIpcOpenMemHandle’
   __pyx_v_status = cudaIpcOpenMemHandle((&__pyx_v_devPtr), __pyx_v_handle_, __pyx_v_flags);
                    ^~~~~~~~~~~~~~~~~~~~
                    hipIpcOpenMemHandle
error: command 'gcc' failed with exit status 1


```

**Comment by leofang** [comment]
I think it's because we missed adding the HIP stubs (https://github.com/cupy/cupy/pull/3290#pullrequestreview-421629756)...Could you try the following patch and see if it builds?
```diff
diff --git a/cupy_backends/cuda/cupy_hip.h b/cupy_backends/cuda/cupy_hip.h
index 273219878..a63a80d18 100644
--- a/cupy_backends/cuda/cupy_hip.h
+++ b/cupy_backends/cuda/cupy_hip.h
@@ -254,6 +254,27 @@ cudaError_t cudaDeviceSetLimit(cudaLimit limit, size_t value) {
     return hipErrorUnknown;
 }
 
+// IPC operations
+cudaError_t cudaIpcCloseMemHandle(void* devPtr) {
+    return hipIpcCloseMemHandle(devPtr);
+}
+
+cudaError_t cudaIpcGetEventHandle(cudaIpcEventHandle_t* handle, cudaEvent_t event) {
+    return hipIpcGetEventHandle(handle, event);
+}
+
+cudaError_t cudaIpcGetMemHandle(cudaIpcMemHandle_t* handle, void* devPtr) {
+    return hipIpcGetMemHandle(handle, devPtr);
+}
+
+cudaError_t cudaIpcOpenEventHandle(cudaEvent_t* event, cudaIpcEventHandle_t handle) {
+    return hipIpcOpenEventHandle(event, handle);
+}
+
+cudaError_t cudaIpcOpenMemHandle(void** devPtr, cudaIpcMemHandle_t handle, unsigned int flags) {
+    return hipIpcOpenMemHandle(devPtr, handle, flags);
+}
+
 // Memory management
 cudaError_t cudaMalloc(void** ptr, size_t size) {
     return hipMalloc(ptr, size);
diff --git a/cupy_backends/cuda/cupy_hip_common.h b/cupy_backends/cuda/cupy_hip_common.h
index 7c9ecc990..8fe8b1019 100644
--- a/cupy_backends/cuda/cupy_hip_common.h
+++ b/cupy_backends/cuda/cupy_hip_common.h
@@ -89,6 +89,10 @@ typedef hipChannelFormatDesc cudaChannelFormatDesc;
 typedef hipResourceDesc cudaResourceDesc;
 typedef hipTextureDesc cudaTextureDesc;
 
+// IPC operations
+typedef hipIpcMemHandle_st cudaIpcMemHandle_t;
+typedef hipIpcEventHandle_st cudaIpcEventHandle_t;
+
 
 ///////////////////////////////////////////////////////////////////////////////
 // blas
```

**Comment by leofang** [comment]
See #3786.
