### ISSUE TITLE
ROCm 7.x: Boolean indexing fails to compile on CuPy 14.0.1 due to 32-bit mask passed to `__shfl_*_sync`

### ISSUE THREAD

**Issue by tedliosu** [cupy/cupy#9742]
## Summary

On ROCm 7.x, CuPy 14.0.1 fails at runtime when performing boolean indexing due to HIPRTC compilation failure. The generated kernel passes a 32-bit literal mask (`0xffffffff`) to `__shfl_*_sync`, but HIP requires a 64-bit mask type.  Expected behavior is that boolean indexing operations succeed without any HIPRTC compilation errors.

This affects both RDNA3 and CDNA3 GPUs.

## Observed Example Error

```
In file included from <built-in>:1:
/tmp/comgr-15736-12-b48b05/include/hiprtc_runtime.h:8136:62: error: static assertion failed due to requirement 'sizeof(unsigned int) == 8': The mask must be a 64-bit integer. Implicitly promoting a smaller integer is almost always an error.
 8136 |   static_assert(__hip_internal::is_integral<MaskT>::value && sizeof(MaskT) == 8,
      |                                                              ^~~~~~~~~~~~~~~~~~
/tmp/comgr-15736-12-b48b05/input/tmp/tmpok6ksj1i/16ca1c7ca24b14a20631daa84c0c853cde516b85.hsaco.cu:26:18: note: in instantiation of function template specialization '__shfl_xor_sync<unsigned int, int>' requested here
   26 |             x += __shfl_xor_sync(0xffffffff, x, j, 64);
      |                  ^
/tmp/comgr-15736-12-b48b05/include/hiprtc_runtime.h:8136:76: note: expression evaluates to '4 == 8'
 8136 |   static_assert(__hip_internal::is_integral<MaskT>::value && sizeof(MaskT) == 8,
      |                                                              ~~~~~~~~~~~~~~^~~~
1 error generated when compiling for gfx942.
```
Full traceback omitted here for brevity; it originates from:
```
_cupy_bsum_shfl → scan → boolean indexing
```
and fails during HIPRTC compilation.

### To Reproduce

Save reproducer as `repro_bool_index.py`:
```py
import cupy as cp

x = cp.arange(2048, dtype=cp.int32)
mask = (x & 1) == 0  # bool mask, half True

y = x[mask]

print("y.shape:", y.shape, "y[:5]:", y[:5].get() if hasattr(y, "get") else y[:5])
```

Clear kernel cache before running:
```bash
rm -rf ~/.cupy/kernel_cache
env ROCR_VISIBLE_DEVICES=[device index here] ROCM_HOME="/opt/rocm" python repro_bool_index.py
```

### Installation

Built from GitHub source

### Environment

```
OS                        : Linux-5.15.0-170-generic-x86_64-with-glibc2.35
Python Version            : 3.10.12
CuPy Version              : 14.0.1
CuPy Platform             : AMD ROCm
NumPy Version             : 2.2.6
SciPy Version             : 1.15.3
Cython Build Version      : 3.1.8
Cython Runtime Version    : 3.1.8
CUDA Root                 : /usr
HIPCC PATH                : /usr/bin/hipcc
CUDA Build Version        : 70226015
CUDA Driver Version       : 70226015
CUDA Runtime Version      : 70226015 (linked to CuPy) / 70226015 (locally installed)
CUDA Extra Include Dirs   : None
cuBLAS Version            : 50200
cuFFT Version             : 10036
cuRAND Version            : 400200
cuSOLVER Version          : (3, 32, 0)
cuSPARSE Version          : 400200
NVRTC Version             : (9, 0)
Thrust Version            : 0
CUB Build Version         : 400200
Jitify Build Version      : None
NCCL Build Version        : 22707
NCCL Runtime Version      : 22707
cuTENSOR Version          : None
cuSPARSELt Build Version  : None
Device 0 Name             : AMD Instinct MI300X VF
Device 0 Arch             : gfx942:sramecc+:xnack-
Device 0 PCI Bus ID       : 0000:ff:00.0
```

### Additional Information

Above reproducer python script was tested on:
* CuPy 14.0.1 PyPI prebuilt wheel with ROCm 7.0.2 system libraries
* CuPy 14.0.1 built from source first with ROCm 7.1.1 on local system, and then with ROCm 7.2.0 in cloud MI300X VM (with the necessary adjustments from [#9622](https://github.com/cupy/cupy/pull/9622) to build against ROCm 7.2.0)

GPUs:
* RX 7600 XT (gfx1102; PyPI wheel tested using `HSA_OVERRIDE_GFX_VERSION=11.0.0`)
* MI300X (gfx942)

Both GPUs fail in the same way.

---

## Root Cause

CuPy generates shuffle intrinsics like:

```cpp
__shfl_xor_sync(0xffffffff, x, j, warp_size);
```

On HIP (ROCm 7.x), `_sync` shuffle intrinsics require the mask argument to be a 64-bit integer type. Passing a 32-bit literal (`0xffffffff`) causes a compile-time static assertion failure in HIPRTC.

This occurs in at least:

* `_cupy_bsum_shfl` (used by `scan` in `cupy/_core/_routines_math.pyx`)
* `_nonzero_kernel_incomplete_scan` (in `cupy/_core/_routines_indexing.pyx`)

Other shuffle-based kernels may be similarly affected.

---

## Notes

* This does not appear to be specific to a single ROCm minor version.
* It affects boolean indexing (`x[mask]`) and any code path that triggers `scan`.
* CUDA builds do not appear to be affected.

**Comment by gpinkert** [comment]
Hi - I already have a fix for this internally at AMD. Once it passes our internal review process, I will make a PR here.

**Comment by gpinkert** [comment]
Hi, please see: https://github.com/cupy/cupy/pull/9748

Can you build a fresh wheel from that branch and check if it solves the Boolean indexing?

**Comment by tedliosu** [comment]
> Hi, please see: [#9748](https://github.com/cupy/cupy/pull/9748)
> 
> Can you build a fresh wheel from that branch and check if it solves the Boolean indexing?

Hello! I built and installed CuPy from the `pull/9748/head` branch merged with the latest `origin/main`, and re-tested.

**Result:**
The boolean indexing repro now works (no HIPRTC compile error), both with and without CUB acceleration.

Tested on MI300X VF (gfx942), ROCm 7.2:

- `rm -rf ~/.cupy/kernel_cache && env ROCR_VISIBLE_DEVICES=0 ROCM_HOME="/opt/rocm" python repro_bool_index.py`:
  - output w/o CUB: `y.shape: (1024,) y[:5]: [0 2 4 6 8]`
  - with `CUPY_ACCELERATORS="cub"` appended in environment variables list: same result

I also tested my `pseudo_gpu_canny_cupy.py` pipeline (which previously hit the same failure path via boolean indexing/scan), and it succeeds both with and without CUB in that same gfx942 and ROCm 7.2 environment.

**Build details:**

- `cupy 15.0.0a1` (editable install) from `/home/hotaisle/cupy_test_hipmask`
- repo HEAD: `3fb36d3c0 Merge remote-tracking branch 'origin/main' into pr-9748-hipmask for proper ROCm 7.2 testing`
- CuPy Platform: AMD ROCm
- Python 3.10.12, NumPy 2.2.6, SciPy 1.15.3
- CUDA Build/Driver/Runtime: 70226015

Happy to re-test on my local RX 7600 XT (gfx1102) once it's free (currently running a long badblocks job; ETA ~March 2).

---

**Question:** I noticed that `cupyx.jit` 64-bit HIP mask usage is gated to ROCm 7.2 and newer. Is the expectation that ROCm < 7.2 continues using CuPy's `hip_workaround.cuh` macros (mask ignored), so 32-bit literals remain acceptable there? Just want to confirm there's no regression risk for ROCm 6.2–7.1 JIT builds.

**Comment by tedliosu** [comment]
**Update:** I retested the `pull/9748/head` branch on my local RDNA3 system as well.

**RX 7600 XT (gfx1102 / wave32), ROCm 7.1.1:**
- `repro_bool_index.py` works (no HIPRTC error), both w/ and w/o `CUPY_ACCELERATORS="cub"`
- my `pseudo_gpu_canny_cupy.py` pipeline also succeeds in both modes

Commands used:
- `rm -rf ~/.cupy/kernel_cache && env ROCR_VISIBLE_DEVICES=0 ROCM_HOME="/opt/rocm" python repro_bool_index.py`
- Same w/ `CUPY_ACCELERATORS="cub"`
- Same approach for `pseudo_gpu_canny_cupy.py`

**Build details:**
- CuPy 15.0.0a1 wheel built via `pip wheel` from PR branch merged w/ `origin/main`.
- repo HEAD: `398a5340a Merge remote-tracking branch 'origin/main' into pr-9748-hipmask`
- Python 3.12.3, NumPy 2.4.2, SciPy 1.17.1
- CUDA Build/Driver/Runtime: 70152802

For reference, `hipconfig` shows ROCm/HIP 7.1.1 locally; earlier I confirmed the same fix on MI300X VF (gfx942 / wave64) w/ ROCm 7.2.
