### ISSUE TITLE
CUDA 8.0 build fails on Windows

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3076]
`master` branch fails to build with Visual Studio 2017 (MSVC 14.16.27023) with CUDA 8.0:

```
C:\Windows\TEMP\tmpxft_00000afc_00000000-65_cupy_thrust.compute_30.ii : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```

This does not happen with CUDA 9.0+.

**Comment by kmaehashi** [comment]
The same issue is happening in v7 branch, but will be fixed with https://github.com/cupy/cupy/pull/3379.

As for v8 master branch, we don't merge this as CUDA 8.0 support will be dropped https://github.com/cupy/cupy/issues/3301

**Comment by emcastillo** [comment]
The error comes from compiling thrust, so it is likely to happen again, and there is a chance it may happen when compiling CUB in windows, so we should be aware of this :)

**Comment by kmaehashi** [comment]
Closing as CUDA 8.0 support will be dropped in v8.
