### PR TITLE
fix cupy.diag() fails for array_likes other than CuPy arrays

### PR DESCRIPTION
**Pull request by hyabe**
By using the latest GitHub master, `cupy.diag()` fails when a list or a tuple is given.

It reproduces as follows:
```
$ python
...
>>> import cupy
>>> cupy.diag((1,2,3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../cupy/cupy/creation/matrix.py", line 28, in diag
    if v.ndim == 1:
AttributeError: 'tuple' object has no attribute 'ndim'
```

### CODE REVIEW

**Comment by okuta** [comment]
Thank you for your PR.

In CuPy, it is standard to take `cupy.ndarray` as argument for performance issue.
I think that it is better to avoid unexpected memory transfer between CPU and GPU.

Would you like to output an exception if the input is `numpy.ndarray`?

**Comment by hyabe** [comment]
I don't have any idea of how `cupy.diag()` should behave for `numpy.ndarray`, so I left it as it was.

[The document](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.diag.html) says "Parameters: v (array-like)" and "Return type: `cupy.ndarray`".
If `numpy.ndarray` is also a kind of "array-like", a return value should be converted to `cupy.ndarray`.
Otherwise,  `cupy.diag()` should check the argument type and raise an exception.

As many CuPy functions don't accept `numpy.ndarray`s as you say, the latter seems a bit more consistent and reasonable way for me.

**Comment by okuta** [comment]
> cupy.diag() should check the argument type and raise an exception.

I want to this. We have to fix document too.
I understood that it is necessary to clear the argument of CuPy functions (#1128). Thank you.

**Comment by hyabe** [comment]
I agree with not to support `numpy.ndarray`.

I have two questions.

First, what happens if the first argument is scalar, e.g. `cp.diag(3, 1)`?
Can I assume that it works as `cp.diag(cp.array([3]), 1)` rather than as `cp.diag(cp.array([[3]]), 1)`?

Next, the following is useful and works on CuPy 4.0.0rc1, will it be invalid?
```
>>> # create a diagonal cupy.ndarray from a 1-dimensional Python list (or can be a 1D tuple)
>>> cp.diag([3, 1, 4])
array([[3, 0, 0],
       [0, 1, 0],
       [0, 0, 4]])
>>> isinstance(cp.diag([3,1,4]), cp.ndarray)
True
```

**Comment by okuta** [comment]
Thanks, I tested CuPy 4.0.0rc1 . It accepts python list. But, that was not intentional behavior.

CuPy provides interface commonality with NumPy. If CuPy dose not accept python lists, users should modify their own code. But, python lists and NumPy arrays are very similar. 

Please give me some time to discuss this matter.

**Comment by okuta** [comment]
I discussed with @beam2d  at offline.
We decided that CuPy functions accepts array like object to improve compatibility with NumPy.

I will restart review this PR.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by hyabe** [comment]
Thank you for the discuss and the review, and sorry for late.
I've fixed the code to always return a CuPy array.

**Comment by okuta** [comment]
LGTM!
