### PR TITLE
Add a few missing stubs for ROCm/HIP build 

### LINKED ISSUE #2681: About cupy build error in HIP (AMD ROCm) environment
Hello,I tried to build an environment based on ROCm for Cupy but failed
 I tried HIP build on "cupy v7.0.0 rc1" but it failed in some environments.
I have built and tried multiple environments and reproduced a similar error.

Env1 
OS Ubuntu 18.04.3
Xeon  E5-2603 v4
gcc 7.4.0
GPU RadeonⅦ
ROCm version 2.9.6
MiOpen Version: 2.1.0.7487-rocm-rel-2.9-6-a5a4129

Env2
Run on Env1
ROCm Docker based env
The same build error was reproduced in the following Dockerfile
https://gist.github.com/KeigoTakamura/188295b7a5a07215d90348c769af3dbc

Env3

OS ubuntu 18.04.3
eGPU Base  Dynabook U63 
CPU Corei5 7300U 
GPU Vega56
ROCm version 2.9.6

The following build errors were confirmed in the above environment

```
cupy/cuda/runtime.cpp: In function 'int __pyx_f_4cupy_4cuda_7runtime_deviceGetByPCIBusId(PyObject*, int)':
cupy/cuda/runtime.cpp:3966:83: error: 'cudaDeviceGetByPCIBusId' was not declared in this scope
   __pyx_v_status = cudaDeviceGetByPCIBusId((&__pyx_v_device), __pyx_v_c_pci_bus_id);
                                                                                   ^
cupy/cuda/runtime.cpp: In function 'PyObject* __pyx_f_4cupy_4cuda_7runtime_deviceGetPCIBusId(int, int)':
cupy/cuda/runtime.cpp:4076:80: error: 'cudaDeviceGetPCIBusId' was not declared in this scope
   __pyx_v_status = cudaDeviceGetPCIBusId(__pyx_v_pci_bus_id, 13, __pyx_v_device);
                                                                                ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
This error could not be reproduced in some environments of ubuntu16.04 LST, but this error was confirmed in multiple environments and machines

### PR DESCRIPTION
**Pull request by leofang**
Follow-ups of #2426 and #2578. Seems to close #2681 based on https://github.com/cupy/cupy/issues/2681#issuecomment-559912154.

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM!
