### ISSUE TITLE
module 'cupy' has no attribute 'corrcoef'

### ISSUE THREAD

**Issue by ssoulhi** [cupy/cupy#2238]
AttributeError                            Traceback (most recent call last)
<ipython-input-88-dac9d0384586> in <module>
----> 1 ccp = cp.corrcoef(df_n_cp)

AttributeError: module 'cupy' has no attribute 'corrcoef'

where type(df_n_cp) is cupy.core.core.ndarray

My environment is:

CuPy Version          : 4.1.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 9000
cuDNN Build Version   : 7102
cuDNN Version         : 7301
NCCL Build Version    : 1000

**Comment by harshalchaudhari35** [comment]
Try updating the CuPy version? It's working on CuPy 6.0 and Cuda 10.1
