### ISSUE TITLE
[BUG] ROCm: the `cupy.cuda.cub` module cannot be built in v8

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4218]
Looks like in CuPy v8 we assumed the `cupy.cuda.cub` module is always built, but the ROCm support was not added until recently (#4027), so an error is raised upon `import cupy`:
```
$ pip install -v cupy    # build from sdist
$ python -c "import cupy"
Traceback (most recent call last):
  File "/home/leofang/miniconda3/envs/cupy_test/lib/python3.7/site-packages/cupy/__init__.py", line 20, in <module>
    from cupy import core  # NOQA
  File "/home/leofang/miniconda3/envs/cupy_test/lib/python3.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
  File "cupy/core/_routines_manipulation.pyx", line 1, in init cupy.core._routines_manipulation
  File "cupy/core/_routines_indexing.pyx", line 1, in init cupy.core._routines_indexing
  File "cupy/core/_routines_math.pyx", line 6, in init cupy.core._routines_math
  File "cupy/core/_reduction.pyx", line 1, in init cupy.core._reduction
  File "cupy/core/_cub_reduction.pyx", line 1, in init cupy.core._cub_reduction
ModuleNotFoundError: No module named 'cupy.cuda.cub'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leofang/miniconda3/envs/cupy_test/lib/python3.7/site-packages/cupy/__init__.py", line 41, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: No module named 'cupy.cuda.cub'
```
I think this can be fixed simply by backporting #4027.

ref: https://stackoverflow.com/questions/64613606/cupy-on-amd-gpu-causing-an-importerror

**Comment by kmaehashi** [comment]
Thanks! Fixed by backporting #4027 (+ #4162).
Will add test in https://github.com/cupy/cupy/pull/4326.

**Comment by leofang** [comment]
Thanks @kmaehashi @emcastillo!

**Comment by ipe-zhangyz** [comment]
Hi @leofang ！I encountered this problem on ROCM 3.9. I read the messages in #4027 , but still not very clear about how this problem was solved. Is the solution merged in any released version of CuPy? I tested v8.1.0, v8.2.0 and v9.0.0a2 on ROCM 3.9 and all of these tests failed due to this problem.

**Comment by leofang** [comment]
@ipe-zhangyz, this is fixed in v8.2 (#4327) and should just work in v9.x (the master branch). Did you install `hipcub` and `rocprim`? They are part of the ROCm libraries but are optional packages, not installed by default when you install the meta package. See the installation guide: https://docs.cupy.dev/en/stable/install_rocm.html.

**Comment by ipe-zhangyz** [comment]
Hello, @leofang , I have hipcub and rocprim installed. And I checked out the master branch of cupy and reinstalled it, unfortunately, the problem still exists:

```
Traceback (most recent call last):
  File "/home/zhangyz/software/miniconda3/envs/cupy_rocm39/lib/python3.8/site-packages/cupy/__init__.py", line 20, in <module>
    from cupy import core  # NOQA
  File "/home/zhangyz/software/miniconda3/envs/cupy_rocm39/lib/python3.8/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
  File "/home/zhangyz/software/miniconda3/envs/cupy_rocm39/lib/python3.8/site-packages/cupy/cuda/__init__.py", line 34, in <module>
    from cupy.cuda import cub  # NOQA
ImportError: cannot import name 'cub' from partially initialized module 'cupy.cuda' (most likely due to a circular import) (/home/zhangyz/software/miniconda3/envs/cupy_rocm39/lib/python3.8/site-packages/cupy/cuda/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "elementwise.py", line 2, in <module>
    import cupy as cp
  File "/home/zhangyz/software/miniconda3/envs/cupy_rocm39/lib/python3.8/site-packages/cupy/__init__.py", line 41, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: cannot import name 'cub' from partially initialized module 'cupy.cuda' (most likely due to a circular import) (/home/zhangyz/software/miniconda3/envs/cupy_rocm39/lib/python3.8/site-packages/cupy/cuda/__init__.py)
```
In the log file generated by `pip install cupy --no-cache-dir -vvvv`, there are logs like this:

```
    Build Environment:
      Include directories: ['/opt/rocm-3.9.1/include/hipcub', '/tmp/pip-req-build-63l97x26/install/../cupy/core/include', '/opt/rocm-3.9.1/include', '/opt/rocm-3.9.1/include/hip', '/opt/rocm-3.9.1/include/rocrand', '/opt/rocm-3.9.1/include/roctracer']
      Library directories: ['/opt/rocm-3.9.1/lib']
      nvcc command       : (not found)
...........
    Modules:
      cuda      : Yes
      cub       : No (version 201005)
        -> nvcc command could not be found in PATH.
        -> Check your PATH environment variable.
      nccl      : Yes (version 2708)
      thrust    : No
        -> nvcc command could not be found in PATH.
        -> Check your PATH environment variable.

    WARNING: Some modules could not be configured.
    CuPy will be installed without these modules.
    Please refer to the Installation Guide for details:
    https://docs.cupy.dev/en/stable/install.html
........................
 copying cupy/core/include/cupy/cub/cub/block/block_radix_sort.cuh -> build/lib.linux-x86_64-3.8/cupy/core/include/cupy/cub/cub/block
  copying cupy/core/include/cupy/cub/cub/block/block_histogram.cuh -> build/lib.linux-x86_64-3.8/cupy/core/include/cupy/cub/cub/block
  copying cupy/core/include/cupy/cub/cub/block/block_store.cuh -> build/lib.linux-x86_64-3.8/cupy/core/include/cupy/cub/cub/block
..................
 Compiling cupy/core/_cub_reduction.pyx because it changed.
................
 [ 4/52] Cythonizing cupy/core/_cub_reduction.pyx
.................
  building 'cupy.core._cub_reduction' extension
  gcc -pthread -B /home/zhangyz/software/miniconda3/envs/cupy_rocm39/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FORCE_INLINES=1 -DCUPY_USE_HIP=1 -D__HIP_PLATFORM_HCC__=1 -DCUPY_CUB_VERSION_CODE=201005 -I/opt/rocm-3.9.1/include/hipcub -I/tmp/pip-req-build-63l97x26/install/../cupy/core/include -I/opt/rocm-3.9.1/include -I/opt/rocm-3.9.1/include/hip -I/opt/rocm-3.9.1/include/rocrand -I/opt/rocm-3.9.1/include/roctracer -I/home/zhangyz/software/miniconda3/envs/cupy_rocm39/include/python3.8 -c cupy/core/_cub_reduction.cpp -o build/temp.linux-x86_64-3.8/cupy/core/_cub_reduction.o -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
..............
copying build/lib.linux-x86_64-3.8/cupy/core/_cub_reduction.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/cupy/core
...............
 copying build/lib.linux-x86_64-3.8/cupy/core/include/cupy/cub/cub/util_type.cuh -> build/bdist.linux-x86_64/wheel/cupy/core/include/cupy/cub/cub
  creating build/bdist.linux-x86_64/wheel/cupy/core/include/cupy/cub/cub/grid
....................
 adding 'cupy/core/_cub_reduction.cpython-38-x86_64-linux-gnu.so'
.......................
 adding 'cupy/cuda/cupy_cub.cu'
....................

```
I'm not sure whether the cub module is built in my case, as there are some hints that conflict with each other in the log. For example, the configuration of modules says there is no cub (maybe it means no cuda cub?), but in the following compilation, there are cub relevant files compiled and dynamic libraries added.  On the same machine, the CuPy v8.0.0 works well with rocm 3.5.0. By the way, my operation system is CentOs 7.6.

**Comment by leofang** [comment]
@ipe-zhangyz Your error log looks specious to me. First, note that the error is different from those reported originally and on SO: yours is
```
ImportError: cannot import name 'cub' from partially initialized module 'cupy.cuda' (most likely due to a circular import)
```
whereas the original error (that we fixed now) is 
```
ModuleNotFoundError: No module named 'cupy.cuda.cub'
```
I think it's suggesting either due to a dirty build, or your env vars were messed up during build time.

For example, if it used to work for you (I think you made it work for quite a while?) but now it doesn't after updating ROCm, likely you need to check your env vars like `ROCM_HOME`, `PATH`, and `LD_LIBRARY_PATH` and see if you include the correct paths to the new ROCm or not.

Also, this part of your log looks weird to me
```
    Modules:
      cuda      : Yes
      cub       : No (version 201005)
        -> nvcc command could not be found in PATH.
        -> Check your PATH environment variable.
      nccl      : Yes (version 2708)
      thrust    : No
        -> nvcc command could not be found in PATH.
        -> Check your PATH environment variable.
```
though in this case I can't say for sure what's wrong. Could you upload the full log generated during `pip install`?

Another thing to try is to clean up the source directory and rebuild. You can either start with a fresh clone of cupy, or do `git clean -fdx` in the existing cupy directory (***WARNING***⚠️: this removes all files that are not part of the git repo).

**Comment by ipe-zhangyz** [comment]
Hello @leofang , thanks for your reply! As you said that there may be something wrong with my  env vars, I switched to a new machine which has not been installed with any version of CuPy to build it form source. However, the problem is the same. I build it as follows:
```
cd ${cupy_source_dir}
git clean -fdx
export HCC_AMDGPU_TARGET=gfx900
export __HIP_PLATFORM_HCC__
export CUPY_INSTALL_USE_HIP=1
export ROCM_HOME=/opt/rocm-3.9.1

pip install . --no-cache-dir -vvvv 
```
Here is the log. There are some errors about _cuda_runtime.h_ not found, which I don't know if matters.

[log.LOG](https://github.com/cupy/cupy/files/5641739/log.LOG)
the PATH var is:
`/public/home/zhangyz/software/miniconda3/envs/cupy_rocm39/bin:/public/home/zhangyz/software/miniconda3/condabin:/opt/rocm-3.9.1/bin:/opt/rocm-3.9.1/hip/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/lib64/qt-3.3/bin:/public/home/zhangyz/perl5/bin:/opt/hpc/software/mpi/hpcx/v2.4.0/hcoll/bin:/opt/hpc/software/mpi/hpcx/v2.4.0/ucx/mt/bin:/opt/hpc/software/mpi/hpcx/v2.4.0/ompi/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/public/home/zhangyz/.local/bin:/public/home/zhangyz/bin`

**Comment by leofang** [comment]
@ipe-zhangyz Thank you. Any chance when it worked previously for you, you were on a machine with CUDA (not ROCm) installed, but now there is none? This would explain and is indeed a bug.

**Comment by ipe-zhangyz** [comment]
@leofang , the machine I used before has only ROCm installed, no CUDA. Some of my test cases used to fail before I followed your instructions. We discussed those problems here #4216 .

**Comment by leofang** [comment]
@ipe-zhangyz I meant previously you didn't have issues with `import cupy`, right? This is very odd, I don't know what's changed after your upgrade to ROCm 3.9. In CuPy's CI we currently always test building and importing against the latest ROCm. 

A few more questions to help me investigate further:
1. Could you run `hipconfig` and post the output here?
2. Are there other versions of ROCm installed on the same system?

Thanks.

**Comment by ipe-zhangyz** [comment]
@leofang , with ROCm 3.5 and CuPy v8.0.0，I have no issue with `import cupy`. 
Currently I have tested CuPy with ROCm 3.5 and ROCm 3.9 on two different machines, both of which have more than one version of ROCm installed. I use `module` (an environment variables management tool) to switch among different versions of ROCm.
I uninstalled the previous CuPy  v8.0.0 on ROCm 3.5 and reinstelled it and got this log:
[log-3.5.LOG](https://github.com/cupy/cupy/files/5646458/log-3.5.LOG)
It seems that there are some major diffenences between the installation of v9 on ROCm 3.9 and v8.0.0 on ROCm 3.5，for example, in v8.0.0, cub module is not configured, instead it is cusolver that is configured:
```
    Modules:
      cuda      : Yes
      cusolver  : Yes
      thrust    : No
        -> nvcc command could not be found in PATH.
        -> Check your PATH environment variable.

    WARNING: Some modules could not be configured.
    CuPy will be installed without these modules.
    Please refer to the Installation Guide for details:
    https://docs.cupy.dev/en/stable/install.html
```
Is this the reason that there is no cub issue in v8.0.0?
Here are the outputs of hipconfig on my two machines, one of which is configured to ROCm 3.5 and the other is ROCm 3.9.

[hipconfig-rocm35.LOG](https://github.com/cupy/cupy/files/5646511/hipconfig-rocm35.LOG)
[hipconfig-rocm39.LOG](https://github.com/cupy/cupy/files/5646512/hipconfig-rocm39.LOG)

To be clear, the two logs are from two different machines, but both of the two machines have multiple versions of ROCm，from rocm 2.9 to  3.9,  installed in different directories, and managed using the `module` tool. On the machine which has both ROCm 3.5 and ROCm 3.9, the CuPy v8.0.0 works with ROCm 3.5，but v8.1.0, v8.2.0 and v9 have the cub issue with ROCm 3.9.

**Comment by leofang** [comment]
Thanks, @ipe-zhangyz. Your hipconfig logs seem legit. Could you do one stupid thing to me? Set
```
export NVCC=/something/does/not/exist
```
and rebuild a case in which you know import CuPy would fail? I feel I was actually very close 🤞

**Comment by ipe-zhangyz** [comment]
@leofang , do you mean to build CuPy in an environment that has only ROCm installed but has an  NVCC env var exported? I tried it as follows:
```
cd ${cupy_source_dir}
git clean -fdx
export HCC_AMDGPU_TARGET=gfx900
export __HIP_PLATFORM_HCC__
export CUPY_INSTALL_USE_HIP=1
export ROCM_HOME=/opt/rocm-3.9.1
export NVCC=/usr/local/cuda 

pip install . --no-cache-dir -vvvv 
```
This cannot install CuPy successfully. Here is the log.
[log-ROCm39-NVCC.LOG](https://github.com/cupy/cupy/files/5646590/log-ROCm39-NVCC.LOG)

**Comment by leofang** [comment]
Thanks, @ipe-zhangyz. This is precisely the error I am looking for. I will try to work out a patch. The reason we didn't notice it so far is that our dev environments always have CUDA & ROCm GPUs coexist (for cost saving)...

**Comment by leofang** [comment]
Let's move the discussion to #4415.
