### PR TITLE
Fix build and import errors for ROCm

### LINKED ISSUE #3783: Build with AMD ROCm3.5.0 failed
Thank you for using and contributing to CuPy!

## Env
  - CuPy version: None
  - OS/Platform: Ubuntu 18.04 LTS
  - ROCm version: 3.5.0
  - cuDNN/NCCL version (if applicable)
  - Python: 3.7.4

I have install ROCm properly, I have compiled and run tensorflow-rocm successfully. But when I compile `cupy`  form source of this repo, I met there errors, Is cupy don't support ROCm3.5.0 ?

## Error messages, stack traces, or logs

```
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcCloseMemHandle(intptr_t, int)’:
cupy_backends/cuda/api/runtime.cpp:5531:20: error: ‘cudaIpcCloseMemHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcCloseMemHandle(((void *)__pyx_v_devPtr));
                    ^~~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5531:20: note: suggested alternative: ‘hipIpcCloseMemHandle’
   __pyx_v_status = cudaIpcCloseMemHandle(((void *)__pyx_v_devPtr));
                    ^~~~~~~~~~~~~~~~~~~~~
                    hipIpcCloseMemHandle
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcGetEventHandle(intptr_t, int)’:
cupy_backends/cuda/api/runtime.cpp:5622:3: error: ‘cudaIpcEventHandle_t’ was not declared in this scope
   cudaIpcEventHandle_t __pyx_v_handle;
   ^~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5622:3: note: suggested alternative: ‘hipIpcEventHandle_t’
   cudaIpcEventHandle_t __pyx_v_handle;
   ^~~~~~~~~~~~~~~~~~~~
   hipIpcEventHandle_t
cupy_backends/cuda/api/runtime.cpp:5640:44: error: ‘__pyx_v_handle’ was not declared in this scope
   __pyx_v_status = cudaIpcGetEventHandle((&__pyx_v_handle), ((cudaEvent_t)__pyx_v_event));
                                            ^~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5640:44: note: suggested alternative: ‘__pyx_k_handle’
   __pyx_v_status = cudaIpcGetEventHandle((&__pyx_v_handle), ((cudaEvent_t)__pyx_v_event));
                                            ^~~~~~~~~~~~~~
                                            __pyx_k_handle
cupy_backends/cuda/api/runtime.cpp:5640:20: error: ‘cudaIpcGetEventHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcGetEventHandle((&__pyx_v_handle), ((cudaEvent_t)__pyx_v_event));
                    ^~~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5640:20: note: suggested alternative: ‘hipIpcGetEventHandle’
   __pyx_v_status = cudaIpcGetEventHandle((&__pyx_v_handle), ((cudaEvent_t)__pyx_v_event));
                    ^~~~~~~~~~~~~~~~~~~~~
                    hipIpcGetEventHandle
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcGetMemHandle(intptr_t, int)’:
cupy_backends/cuda/api/runtime.cpp:5766:3: error: ‘cudaIpcMemHandle_t’ was not declared in this scope
   cudaIpcMemHandle_t __pyx_v_handle;
   ^~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5766:3: note: suggested alternative: ‘hipIpcMemHandle_t’
   cudaIpcMemHandle_t __pyx_v_handle;
   ^~~~~~~~~~~~~~~~~~
   hipIpcMemHandle_t
cupy_backends/cuda/api/runtime.cpp:5784:42: error: ‘__pyx_v_handle’ was not declared in this scope
   __pyx_v_status = cudaIpcGetMemHandle((&__pyx_v_handle), ((void *)__pyx_v_devPtr));
                                          ^~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5784:42: note: suggested alternative: ‘__pyx_k_handle’
   __pyx_v_status = cudaIpcGetMemHandle((&__pyx_v_handle), ((void *)__pyx_v_devPtr));
                                          ^~~~~~~~~~~~~~
                                          __pyx_k_handle
cupy_backends/cuda/api/runtime.cpp:5784:20: error: ‘cudaIpcGetMemHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcGetMemHandle((&__pyx_v_handle), ((void *)__pyx_v_devPtr));
                    ^~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5784:20: note: suggested alternative: ‘hipIpcGetMemHandle’
   __pyx_v_status = cudaIpcGetMemHandle((&__pyx_v_handle), ((void *)__pyx_v_devPtr));
                    ^~~~~~~~~~~~~~~~~~~
                    hipIpcGetMemHandle
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcOpenEventHandle(PyObject*, int)’:
cupy_backends/cuda/api/runtime.cpp:5911:3: error: ‘cudaIpcEventHandle_t’ was not declared in this scope
   cudaIpcEventHandle_t __pyx_v_handle_;
   ^~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5911:3: note: suggested alternative: ‘hipIpcEventHandle_t’
   cudaIpcEventHandle_t __pyx_v_handle_;
   ^~~~~~~~~~~~~~~~~~~~
   hipIpcEventHandle_t
cupy_backends/cuda/api/runtime.cpp:5927:12: error: ‘__pyx_v_handle_’ was not declared in this scope
   memcpy(&(__pyx_v_handle_.reserved[0]), __pyx_t_1, sizeof(__pyx_v_handle_.reserved[0]) * (64));
            ^~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5927:12: note: suggested alternative: ‘__pyx_v_handle’
   memcpy(&(__pyx_v_handle_.reserved[0]), __pyx_t_1, sizeof(__pyx_v_handle_.reserved[0]) * (64));
            ^~~~~~~~~~~~~~~
            __pyx_v_handle
cupy_backends/cuda/api/runtime.cpp:5936:20: error: ‘cudaIpcOpenEventHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcOpenEventHandle((&__pyx_v_event), __pyx_v_handle_);
                    ^~~~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:5936:20: note: suggested alternative: ‘hipIpcOpenEventHandle’
   __pyx_v_status = cudaIpcOpenEventHandle((&__pyx_v_event), __pyx_v_handle_);
                    ^~~~~~~~~~~~~~~~~~~~~~
                    hipIpcOpenEventHandle
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_13cupy_backends_4cuda_3api_7runtime_ipcOpenMemHandle(PyObject*, int, __pyx_opt_args_13cupy_backends_4cuda_3api_7runtime_ipcOpenMemHandle*)’:
cupy_backends/cuda/api/runtime.cpp:6036:3: error: ‘cudaIpcMemHandle_t’ was not declared in this scope
   cudaIpcMemHandle_t __pyx_v_handle_;
   ^~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:6036:3: note: suggested alternative: ‘hipIpcMemHandle_t’
   cudaIpcMemHandle_t __pyx_v_handle_;
   ^~~~~~~~~~~~~~~~~~
   hipIpcMemHandle_t
cupy_backends/cuda/api/runtime.cpp:6057:12: error: ‘__pyx_v_handle_’ was not declared in this scope
   memcpy(&(__pyx_v_handle_.reserved[0]), __pyx_t_1, sizeof(__pyx_v_handle_.reserved[0]) * (64));
            ^~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:6057:12: note: suggested alternative: ‘__pyx_v_handle’
   memcpy(&(__pyx_v_handle_.reserved[0]), __pyx_t_1, sizeof(__pyx_v_handle_.reserved[0]) * (64));
            ^~~~~~~~~~~~~~~
            __pyx_v_handle
cupy_backends/cuda/api/runtime.cpp:6066:20: error: ‘cudaIpcOpenMemHandle’ was not declared in this scope
   __pyx_v_status = cudaIpcOpenMemHandle((&__pyx_v_devPtr), __pyx_v_handle_, __pyx_v_flags);
                    ^~~~~~~~~~~~~~~~~~~~
cupy_backends/cuda/api/runtime.cpp:6066:20: note: suggested alternative: ‘hipIpcOpenMemHandle’
   __pyx_v_status = cudaIpcOpenMemHandle((&__pyx_v_devPtr), __pyx_v_handle_, __pyx_v_flags);
                    ^~~~~~~~~~~~~~~~~~~~
                    hipIpcOpenMemHandle
error: command 'gcc' failed with exit status 1


```

### LINKED ISSUE #3788: Building `cupy.cuda.thrust` with ROCm 3.5.0 fails
After #3786, the next error I encountered with ROCm 3.5.0 + Radeon VII is this (`error: unknown type name '__host__'`):
```    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************

    Build Environment:
      Include directories: ['/home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/cub', '/home/leo/dev/cupy_rocm35/install/../cupy/core/include', '/opt/rocm/include', '/opt/rocm/rocrand/include']
      Library directories: ['/opt/rocm/lib', '/opt/rocm/rocrand/lib']
      nvcc command       : ['/usr/bin/nvcc']

    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
      ROCM_HOME       : /opt/rocm

    Modules:
      cuda      : Yes
      cusolver  : Yes
      thrust    : Yes
    ************************************************************

    building 'cupy.cuda.thrust' extension
    gcc -pthread -B /home/leo/miniconda3/envs/cupy_rocm35_dev/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FORCE_INLINES=1 -DCUPY_USE_HIP=1 -D__HIP_PLATFORM_HCC__=1 -I/home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/cub -I/home/leo/dev/cupy_rocm35/install/../cupy/core/include -I/opt/rocm/include -I/opt/rocm/rocrand/include -I/home/leo/miniconda3/envs/cupy_rocm35_dev/include/python3.7m -c cupy/cuda/thrust.cpp -o build/temp.linux-x86_64-3.7/cupy/cuda/thrust.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    HIPCC options: ['-O2', '-fPIC']
    /opt/rocm/bin/hipcc -D_FORCE_INLINES=1 -DCUPY_USE_HIP=1 -D__HIP_PLATFORM_HCC__=1 -I/home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/cub -I/home/leo/dev/cupy_rocm35/install/../cupy/core/include -I/opt/rocm/include -I/opt/rocm/rocrand/include -I/home/leo/miniconda3/envs/cupy_rocm35_dev/include/python3.7m -c cupy/cuda/cupy_thrust.cu -o build/temp.linux-x86_64-3.7/cupy/cuda/cupy_thrust.o -O2 -fPIC
    HIP_PATH=/opt/rocm-3.5.0/hip
    HIP_PLATFORM=hcc
    HIP_COMPILER=clang
    HIP_RUNTIME=ROCclr
    HIP_ROCCLR_HOME=/opt/rocm-3.5.0/hip
    HIP_CLANG_PATH=/opt/rocm-3.5.0/llvm/bin
    HIP_CLANG_INCLUDE_PATH=/opt/rocm-3.5.0/llvm/lib/clang/11.0.0/include
    HIP_INCLUDE_PATH=/opt/rocm-3.5.0/hip/include
    HIP_LIB_PATH=/opt/rocm-3.5.0/hip/lib
    DEVICE_LIB_PATH=/opt/rocm-3.5.0/lib
    hipcc-args: -D_FORCE_INLINES=1 -DCUPY_USE_HIP=1 -D__HIP_PLATFORM_HCC__=1 -I/home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/cub -I/home/leo/dev/cupy_rocm35/install/../cupy/core/include -I/opt/rocm/include -I/opt/rocm/rocrand/include -I/home/leo/miniconda3/envs/cupy_rocm35_dev/include/python3.7m -c cupy/cuda/cupy_thrust.cu -o build/temp.linux-x86_64-3.7/cupy/cuda/cupy_thrust.o -O2 -fPIC
    hipcc-cmd: /opt/rocm-3.5.0/llvm/bin/clang++ -D__HIP_ROCclr__ -std=c++11 -isystem /opt/rocm-3.5.0/llvm/lib/clang/11.0.0/include/.. -isystem /opt/rocm-3.5.0/hsa/include -D__HIP_ROCclr__ -isystem /opt/rocm-3.5.0/hip/include -D__HIP_ARCH_GFX906__=1  --cuda-gpu-arch=gfx906 -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false  --hip-device-lib-path=/opt/rocm-3.5.0/lib -fhip-new-launch-api  -D\_FORCE\_INLINES=1 -DCUPY\_USE\_HIP=1 -D\_\_HIP\_PLATFORM\_HCC\_\_=1 -I\/home\/leo\/dev\/cupy\_rocm35\/install\/..\/cupy\/core\/include\/cupy\/cub -I\/home\/leo\/dev\/cupy\_rocm35\/install\/..\/cupy\/core\/include -I\/opt\/rocm\/include -I\/opt\/rocm\/rocrand\/include -I\/home\/leo\/miniconda3\/envs\/cupy\_rocm35\_dev\/include\/python3.7m -c -x hip cupy\/cuda\/cupy\_thrust.cu -o build/temp.linux-x86_64-3.7/cupy/cuda/cupy_thrust.o -O2 -fPIC
    In file included from cupy/cuda/cupy_thrust.cu:1:
    In file included from /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/type_dispatcher.cuh:4:
    In file included from /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex.cuh:3:
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:82:10: error: unknown type name '__host__'
      inline __host__ __device__ complex(const T& re);
             ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:82:3: error: 'inline' can only appear on functions
      inline __host__ __device__ complex(const T& re);
      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:82:29: error: expected ';' at end of declaration list
      inline __host__ __device__ complex(const T& re);
                                ^
                                ;
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:89:10: error: unknown type name '__host__'
      inline __host__ __device__ complex(const T& re, const T& im);
             ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:89:3: error: 'inline' can only appear on functions
      inline __host__ __device__ complex(const T& re, const T& im);
      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:89:19: error: duplicate member '__device__'
      inline __host__ __device__ complex(const T& re, const T& im);
                      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:82:19: note: previous declaration is here
      inline __host__ __device__ complex(const T& re);
                      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:89:29: error: expected ';' at end of declaration list
      inline __host__ __device__ complex(const T& re, const T& im);
                                ^
                                ;
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:93:10: error: unknown type name '__host__'
      inline __host__ __device__ complex();
             ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:93:3: error: 'inline' can only appear on functions
      inline __host__ __device__ complex();
      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:93:19: error: duplicate member '__device__'
      inline __host__ __device__ complex();
                      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:82:19: note: previous declaration is here
      inline __host__ __device__ complex(const T& re);
                      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:93:29: error: expected ';' at end of declaration list
      inline __host__ __device__ complex();
                                ^
                                ;
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:100:10: error: unknown type name '__host__'
      inline __host__ __device__ complex(const complex<T>& z);
             ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:100:3: error: 'inline' can only appear on functions
      inline __host__ __device__ complex(const complex<T>& z);
      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:100:19: error: duplicate member '__device__'
      inline __host__ __device__ complex(const complex<T>& z);
                      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:82:19: note: previous declaration is here
      inline __host__ __device__ complex(const T& re);
                      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:100:29: error: expected ';' at end of declaration list
      inline __host__ __device__ complex(const complex<T>& z);
                                ^
                                ;
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:110:10: error: unknown type name '__host__'
      inline __host__ __device__ complex(const complex<X>& z);
             ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:110:19: error: member '__device__' declared as a template
      inline __host__ __device__ complex(const complex<X>& z);
                      ^
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:110:29: error: expected ';' at end of declaration list
      inline __host__ __device__ complex(const complex<X>& z);
                                ^
                                ;
    /home/leo/dev/cupy_rocm35/install/../cupy/core/include/cupy/complex/complex.h:119:10: error: unknown type name '__host__'
      inline __host__ __device__ complex& operator=(const T& re);
             ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated when compiling for gfx906.
    error: command '/opt/rocm/bin/hipcc' failed with exit status 1
```

The reason is the recent introduction of native complex number support to Thrust (#3546). The solution is to make `hip_runtime.h` included (https://github.com/ROCm-Developer-Tools/HIP/issues/441). I'll send a PR to fix this.

### LINKED ISSUE #3789: "rocsolver" is a missing dependency for CuPy + ROCm 3.5.0
After fixing #3783 and #3788, the 3rd error I ran into is missing `librocsolver.so`:
```
$ python -c "import cupy"
Traceback (most recent call last):
  File "/home/leo/dev/cupy_rocm35/cupy/__init__.py", line 19, in <module>
    from cupy import core  # NOQA
  File "/home/leo/dev/cupy_rocm35/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: librocsolver.so.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leo/dev/cupy_rocm35/cupy/__init__.py", line 40, in <module>
    raise ImportError(msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: librocsolver.so.0: cannot open shared object file: No such file or directory
```
which is not listed in the required ROCm packages: 
https://docs.cupy.dev/en/latest/install_rocm.html#requirements

### PR DESCRIPTION
**Pull request by leofang**
Fix https://github.com/cupy/cupy/pull/3290#pullrequestreview-421629756. Fix #3783. 
Fix #3788.
Fix #3789.
Take over #3796.

**(UPDATE):** This PR now includes a few more fixes (ongoing) to make CuPy build against ROCm 3.5.0 and importable:
- Add missing stubs and docs for IPC handles
- Fix Thrust build
- Update docs (make `rocsolver` a dependency)

~~Pending @alphaRGB's report.~~

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
I think HIP has supported all of the five APIs despite there is discrepancy in their online docs (ref: https://github.com/ROCm-Developer-Tools/HIP/issues/728#issuecomment-674243538).

**Comment by leofang** [comment]
CI is misbehaving again...retry.

Jenkins, test this please

**Comment by leofang** [comment]
I verified this PR works with ROCm 3.5.0 and the latest master. But there're other problems, for which I will open an issue and send a PR.

**Comment by leofang** [comment]
After fixing #3789 I ran into this...😞 
```
Traceback (most recent call last):
  File "/home/leo/dev/cupy_rocm35/cupy/__init__.py", line 19, in <module>
    from cupy import core  # NOQA
  File "/home/leo/dev/cupy_rocm35/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
    # distutils: language = c++
  File "/home/leo/dev/cupy_rocm35/cupy/cuda/__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/leo/dev/cupy_rocm35/cupy/cuda/compiler.py", line 10, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 1, in init cupy.cuda.device
    # distutils: language = c++
ImportError: /home/leo/dev/cupy_rocm35/cupy_backends/cuda/api/runtime.cpython-37m-x86_64-linux-gnu.so: undefined symbol: hipIpcOpenEventHandle

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leo/dev/cupy_rocm35/cupy/__init__.py", line 40, in <module>
    raise ImportError(msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: /home/leo/dev/cupy_rocm35/cupy_backends/cuda/api/runtime.cpython-37m-x86_64-linux-gnu.so: undefined symbol: hipIpcOpenEventHandle
```

I'll resume investigation later. Not sure if it's because I put the stubs in the wrong place, or because HIP actually does not support it.

**Comment by leofang** [comment]
Alright, fixed it. It seems to be the latter:

> because HIP actually does not support it.

The support was recently added in https://github.com/ROCm-Developer-Tools/HIP/pull/1996, but it didn't go into ROCm 3.5.0...Disable it for now.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
@alphaRGB @emcastillo This should now fully work for ROCm 3.5.0.

**Comment by leofang** [comment]
36a3c47 adds the stubs missing in #3719.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
I think the current `cupy.py3.amd` configuration does not set `LD_LIBRARY_PATH` properly, so the linker cannot find ROCm/HIP libraries. @kmaehashi I will tweak the config around in this PR.

**Comment by leofang** [comment]
hmmm, not sure what's wrong with `ld`. Maybe we need to set `LDFLAGS`? I don't need that on my machine, though...

**Comment by leofang** [comment]
@kmaehashi When you have time, please check why the linker cannot find hiprtc and hip_hcc. I think we have everything installed, and the installation steps are almost identical to what I've done locally. 

Also, it seems ROCm 3.7.0 just came out today...=_____= Can we (and how to?) lock the CI to 3.5.0 for the moment? I don't have the bandwidth to test different versions...

**Comment by leofang** [comment]
(And feel free to push to my branch if needed!)

**Review by emcastillo — APPROVED** [review]

**Review by emcastillo — APPROVED** [review]

**Comment by leofang** [comment]
Thanks @kmaehashi @emcastillo!
