### ISSUE TITLE
Cupy dose not working on ubuntu 18.04

### ISSUE THREAD

**Issue by ToukiLiu** [cupy/cupy#2853]
Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version 7.0.0
  - OS/Platform Ubuntu 18.04
  - CUDA version 9.0
  - cuDNN/NCCL version 7.6.5 (for cuda 9.0)
  - GPU NVIDIA GTX580
  - Driver version 390.116

Code 1:
```
import cupy as cp
x = cp.arange(6).reshape(2, 3).astype('f')
```
Error msg 1:
```
NVRTC compilation error: nvrtc: error: invalid value for --gpu-architecture (-arch)

-----
Name:
Options: -I/home/liu/.local/lib/python2.7/site-packages/cupy/core/include -I /usr/local/cuda-9.0/include -ftz=true -arch=compute_20
CUDA source:
1
-----
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liu/.local/lib/python2.7/site-packages/cupy/creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/core/_kernel.pyx", line 864, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 876, in cupy.core._kernel.ufunc._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 638, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 166, in cupy.core.core.compile_with_cache
  File "/home/liu/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 136, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/home/liu/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 97, in _preprocess
    result = prog.compile(options)
  File "/home/liu/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 250, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)
```

Code 2:
```
import cupy as cp
cp.random.random_sample(10)
```
Error msg 2:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liu/.local/lib/python3.6/site-packages/cupy/random/sample.py", line 161, in random_sample
    return rs.random_sample(size=size, dtype=dtype)
  File "/home/liu/.local/lib/python3.6/site-packages/cupy/random/generator.py", line 540, in random_sample
    out = self._random_sample_raw(size, dtype)
  File "/home/liu/.local/lib/python3.6/site-packages/cupy/random/generator.py", line 528, in _random_sample_raw
    func(self._generator, out.data.ptr, out.size)
  File "cupy/cuda/curand.pyx", line 158, in cupy.cuda.curand.generateUniformDouble
  File "cupy/cuda/curand.pyx", line 162, in cupy.cuda.curand.generateUniformDouble
  File "cupy/cuda/curand.pyx", line 86, in cupy.cuda.curand.check_status
cupy.cuda.curand.CURANDError: CURAND_STATUS_LAUNCH_FAILURE
```

**Comment by toslunar** [comment]
It seems answered in https://stackoverflow.com/questions/59451428.
